// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: repo-command-response-proto.proto

package net.named_data.jndn.tests.repo_ng;

public final class RepoCommandResponseProto {
  private RepoCommandResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RepoCommandResponseMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;
    /**
     * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
     *
     * <pre>
     * A RepoCommandResponseMessage has one RepoCommandResponse.
     * </pre>
     */
    boolean hasRepoCommandResponse();
    /**
     * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
     *
     * <pre>
     * A RepoCommandResponseMessage has one RepoCommandResponse.
     * </pre>
     */
    net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse getRepoCommandResponse();
    /**
     * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
     *
     * <pre>
     * A RepoCommandResponseMessage has one RepoCommandResponse.
     * </pre>
     */
    net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponseOrBuilder getRepoCommandResponseOrBuilder();
  }
  /**
   * Protobuf type {@code net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage}
   *
   * <pre>
   * Protobuf has no "outer" message type, so we need to put the TLV RepoCommandResponse
   * message inside an outer "typeless" RepoCommandResponseMessage.
   * </pre>
   */
  public static final class RepoCommandResponseMessage extends
      com.google.protobuf.GeneratedMessage
      implements RepoCommandResponseMessageOrBuilder {
    // Use RepoCommandResponseMessage.newBuilder() to construct.
    private RepoCommandResponseMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RepoCommandResponseMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RepoCommandResponseMessage defaultInstance;
    public static RepoCommandResponseMessage getDefaultInstance() {
      return defaultInstance;
    }

    public RepoCommandResponseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RepoCommandResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 1658: {
              net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = repoCommandResponse_.toBuilder();
              }
              repoCommandResponse_ = input.readMessage(net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(repoCommandResponse_);
                repoCommandResponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.class, net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<RepoCommandResponseMessage> PARSER =
        new com.google.protobuf.AbstractParser<RepoCommandResponseMessage>() {
      public RepoCommandResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RepoCommandResponseMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RepoCommandResponseMessage> getParserForType() {
      return PARSER;
    }

    public interface RepoCommandResponseOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional uint64 process_id = 206;
      /**
       * <code>optional uint64 process_id = 206;</code>
       */
      boolean hasProcessId();
      /**
       * <code>optional uint64 process_id = 206;</code>
       */
      long getProcessId();

      // required uint64 status_code = 208;
      /**
       * <code>required uint64 status_code = 208;</code>
       */
      boolean hasStatusCode();
      /**
       * <code>required uint64 status_code = 208;</code>
       */
      long getStatusCode();

      // optional uint64 start_block_id = 204;
      /**
       * <code>optional uint64 start_block_id = 204;</code>
       */
      boolean hasStartBlockId();
      /**
       * <code>optional uint64 start_block_id = 204;</code>
       */
      long getStartBlockId();

      // optional uint64 end_block_id = 205;
      /**
       * <code>optional uint64 end_block_id = 205;</code>
       */
      boolean hasEndBlockId();
      /**
       * <code>optional uint64 end_block_id = 205;</code>
       */
      long getEndBlockId();

      // optional uint64 insert_num = 209;
      /**
       * <code>optional uint64 insert_num = 209;</code>
       */
      boolean hasInsertNum();
      /**
       * <code>optional uint64 insert_num = 209;</code>
       */
      long getInsertNum();

      // optional uint64 delete_num = 210;
      /**
       * <code>optional uint64 delete_num = 210;</code>
       */
      boolean hasDeleteNum();
      /**
       * <code>optional uint64 delete_num = 210;</code>
       */
      long getDeleteNum();
    }
    /**
     * Protobuf type {@code net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse}
     */
    public static final class RepoCommandResponse extends
        com.google.protobuf.GeneratedMessage
        implements RepoCommandResponseOrBuilder {
      // Use RepoCommandResponse.newBuilder() to construct.
      private RepoCommandResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private RepoCommandResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final RepoCommandResponse defaultInstance;
      public static RepoCommandResponse getDefaultInstance() {
        return defaultInstance;
      }

      public RepoCommandResponse getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private RepoCommandResponse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 1632: {
                bitField0_ |= 0x00000004;
                startBlockId_ = input.readUInt64();
                break;
              }
              case 1640: {
                bitField0_ |= 0x00000008;
                endBlockId_ = input.readUInt64();
                break;
              }
              case 1648: {
                bitField0_ |= 0x00000001;
                processId_ = input.readUInt64();
                break;
              }
              case 1664: {
                bitField0_ |= 0x00000002;
                statusCode_ = input.readUInt64();
                break;
              }
              case 1672: {
                bitField0_ |= 0x00000010;
                insertNum_ = input.readUInt64();
                break;
              }
              case 1680: {
                bitField0_ |= 0x00000020;
                deleteNum_ = input.readUInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_RepoCommandResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_RepoCommandResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.class, net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.Builder.class);
      }

      public static com.google.protobuf.Parser<RepoCommandResponse> PARSER =
          new com.google.protobuf.AbstractParser<RepoCommandResponse>() {
        public RepoCommandResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RepoCommandResponse(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<RepoCommandResponse> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional uint64 process_id = 206;
      public static final int PROCESS_ID_FIELD_NUMBER = 206;
      private long processId_;
      /**
       * <code>optional uint64 process_id = 206;</code>
       */
      public boolean hasProcessId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 process_id = 206;</code>
       */
      public long getProcessId() {
        return processId_;
      }

      // required uint64 status_code = 208;
      public static final int STATUS_CODE_FIELD_NUMBER = 208;
      private long statusCode_;
      /**
       * <code>required uint64 status_code = 208;</code>
       */
      public boolean hasStatusCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 status_code = 208;</code>
       */
      public long getStatusCode() {
        return statusCode_;
      }

      // optional uint64 start_block_id = 204;
      public static final int START_BLOCK_ID_FIELD_NUMBER = 204;
      private long startBlockId_;
      /**
       * <code>optional uint64 start_block_id = 204;</code>
       */
      public boolean hasStartBlockId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 start_block_id = 204;</code>
       */
      public long getStartBlockId() {
        return startBlockId_;
      }

      // optional uint64 end_block_id = 205;
      public static final int END_BLOCK_ID_FIELD_NUMBER = 205;
      private long endBlockId_;
      /**
       * <code>optional uint64 end_block_id = 205;</code>
       */
      public boolean hasEndBlockId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 end_block_id = 205;</code>
       */
      public long getEndBlockId() {
        return endBlockId_;
      }

      // optional uint64 insert_num = 209;
      public static final int INSERT_NUM_FIELD_NUMBER = 209;
      private long insertNum_;
      /**
       * <code>optional uint64 insert_num = 209;</code>
       */
      public boolean hasInsertNum() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 insert_num = 209;</code>
       */
      public long getInsertNum() {
        return insertNum_;
      }

      // optional uint64 delete_num = 210;
      public static final int DELETE_NUM_FIELD_NUMBER = 210;
      private long deleteNum_;
      /**
       * <code>optional uint64 delete_num = 210;</code>
       */
      public boolean hasDeleteNum() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint64 delete_num = 210;</code>
       */
      public long getDeleteNum() {
        return deleteNum_;
      }

      private void initFields() {
        processId_ = 0L;
        statusCode_ = 0L;
        startBlockId_ = 0L;
        endBlockId_ = 0L;
        insertNum_ = 0L;
        deleteNum_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasStatusCode()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeUInt64(204, startBlockId_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeUInt64(205, endBlockId_);
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt64(206, processId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt64(208, statusCode_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeUInt64(209, insertNum_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeUInt64(210, deleteNum_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(204, startBlockId_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(205, endBlockId_);
        }
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(206, processId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(208, statusCode_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(209, insertNum_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(210, deleteNum_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_RepoCommandResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_RepoCommandResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.class, net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.Builder.class);
        }

        // Construct using net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          processId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          statusCode_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          startBlockId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          endBlockId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000008);
          insertNum_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000010);
          deleteNum_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_RepoCommandResponse_descriptor;
        }

        public net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse getDefaultInstanceForType() {
          return net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.getDefaultInstance();
        }

        public net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse build() {
          net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse buildPartial() {
          net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse result = new net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.processId_ = processId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.statusCode_ = statusCode_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.startBlockId_ = startBlockId_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.endBlockId_ = endBlockId_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.insertNum_ = insertNum_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.deleteNum_ = deleteNum_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse) {
            return mergeFrom((net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse other) {
          if (other == net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.getDefaultInstance()) return this;
          if (other.hasProcessId()) {
            setProcessId(other.getProcessId());
          }
          if (other.hasStatusCode()) {
            setStatusCode(other.getStatusCode());
          }
          if (other.hasStartBlockId()) {
            setStartBlockId(other.getStartBlockId());
          }
          if (other.hasEndBlockId()) {
            setEndBlockId(other.getEndBlockId());
          }
          if (other.hasInsertNum()) {
            setInsertNum(other.getInsertNum());
          }
          if (other.hasDeleteNum()) {
            setDeleteNum(other.getDeleteNum());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasStatusCode()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional uint64 process_id = 206;
        private long processId_ ;
        /**
         * <code>optional uint64 process_id = 206;</code>
         */
        public boolean hasProcessId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional uint64 process_id = 206;</code>
         */
        public long getProcessId() {
          return processId_;
        }
        /**
         * <code>optional uint64 process_id = 206;</code>
         */
        public Builder setProcessId(long value) {
          bitField0_ |= 0x00000001;
          processId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint64 process_id = 206;</code>
         */
        public Builder clearProcessId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          processId_ = 0L;
          onChanged();
          return this;
        }

        // required uint64 status_code = 208;
        private long statusCode_ ;
        /**
         * <code>required uint64 status_code = 208;</code>
         */
        public boolean hasStatusCode() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required uint64 status_code = 208;</code>
         */
        public long getStatusCode() {
          return statusCode_;
        }
        /**
         * <code>required uint64 status_code = 208;</code>
         */
        public Builder setStatusCode(long value) {
          bitField0_ |= 0x00000002;
          statusCode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 status_code = 208;</code>
         */
        public Builder clearStatusCode() {
          bitField0_ = (bitField0_ & ~0x00000002);
          statusCode_ = 0L;
          onChanged();
          return this;
        }

        // optional uint64 start_block_id = 204;
        private long startBlockId_ ;
        /**
         * <code>optional uint64 start_block_id = 204;</code>
         */
        public boolean hasStartBlockId() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional uint64 start_block_id = 204;</code>
         */
        public long getStartBlockId() {
          return startBlockId_;
        }
        /**
         * <code>optional uint64 start_block_id = 204;</code>
         */
        public Builder setStartBlockId(long value) {
          bitField0_ |= 0x00000004;
          startBlockId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint64 start_block_id = 204;</code>
         */
        public Builder clearStartBlockId() {
          bitField0_ = (bitField0_ & ~0x00000004);
          startBlockId_ = 0L;
          onChanged();
          return this;
        }

        // optional uint64 end_block_id = 205;
        private long endBlockId_ ;
        /**
         * <code>optional uint64 end_block_id = 205;</code>
         */
        public boolean hasEndBlockId() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional uint64 end_block_id = 205;</code>
         */
        public long getEndBlockId() {
          return endBlockId_;
        }
        /**
         * <code>optional uint64 end_block_id = 205;</code>
         */
        public Builder setEndBlockId(long value) {
          bitField0_ |= 0x00000008;
          endBlockId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint64 end_block_id = 205;</code>
         */
        public Builder clearEndBlockId() {
          bitField0_ = (bitField0_ & ~0x00000008);
          endBlockId_ = 0L;
          onChanged();
          return this;
        }

        // optional uint64 insert_num = 209;
        private long insertNum_ ;
        /**
         * <code>optional uint64 insert_num = 209;</code>
         */
        public boolean hasInsertNum() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional uint64 insert_num = 209;</code>
         */
        public long getInsertNum() {
          return insertNum_;
        }
        /**
         * <code>optional uint64 insert_num = 209;</code>
         */
        public Builder setInsertNum(long value) {
          bitField0_ |= 0x00000010;
          insertNum_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint64 insert_num = 209;</code>
         */
        public Builder clearInsertNum() {
          bitField0_ = (bitField0_ & ~0x00000010);
          insertNum_ = 0L;
          onChanged();
          return this;
        }

        // optional uint64 delete_num = 210;
        private long deleteNum_ ;
        /**
         * <code>optional uint64 delete_num = 210;</code>
         */
        public boolean hasDeleteNum() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional uint64 delete_num = 210;</code>
         */
        public long getDeleteNum() {
          return deleteNum_;
        }
        /**
         * <code>optional uint64 delete_num = 210;</code>
         */
        public Builder setDeleteNum(long value) {
          bitField0_ |= 0x00000020;
          deleteNum_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint64 delete_num = 210;</code>
         */
        public Builder clearDeleteNum() {
          bitField0_ = (bitField0_ & ~0x00000020);
          deleteNum_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse)
      }

      static {
        defaultInstance = new RepoCommandResponse(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse)
    }

    private int bitField0_;
    // required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;
    public static final int REPO_COMMAND_RESPONSE_FIELD_NUMBER = 207;
    private net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse repoCommandResponse_;
    /**
     * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
     *
     * <pre>
     * A RepoCommandResponseMessage has one RepoCommandResponse.
     * </pre>
     */
    public boolean hasRepoCommandResponse() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
     *
     * <pre>
     * A RepoCommandResponseMessage has one RepoCommandResponse.
     * </pre>
     */
    public net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse getRepoCommandResponse() {
      return repoCommandResponse_;
    }
    /**
     * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
     *
     * <pre>
     * A RepoCommandResponseMessage has one RepoCommandResponse.
     * </pre>
     */
    public net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponseOrBuilder getRepoCommandResponseOrBuilder() {
      return repoCommandResponse_;
    }

    private void initFields() {
      repoCommandResponse_ = net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRepoCommandResponse()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getRepoCommandResponse().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(207, repoCommandResponse_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(207, repoCommandResponse_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage}
     *
     * <pre>
     * Protobuf has no "outer" message type, so we need to put the TLV RepoCommandResponse
     * message inside an outer "typeless" RepoCommandResponseMessage.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.class, net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.Builder.class);
      }

      // Construct using net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRepoCommandResponseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (repoCommandResponseBuilder_ == null) {
          repoCommandResponse_ = net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.getDefaultInstance();
        } else {
          repoCommandResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_descriptor;
      }

      public net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage getDefaultInstanceForType() {
        return net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.getDefaultInstance();
      }

      public net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage build() {
        net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage buildPartial() {
        net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage result = new net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (repoCommandResponseBuilder_ == null) {
          result.repoCommandResponse_ = repoCommandResponse_;
        } else {
          result.repoCommandResponse_ = repoCommandResponseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage) {
          return mergeFrom((net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage other) {
        if (other == net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.getDefaultInstance()) return this;
        if (other.hasRepoCommandResponse()) {
          mergeRepoCommandResponse(other.getRepoCommandResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRepoCommandResponse()) {
          
          return false;
        }
        if (!getRepoCommandResponse().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;
      private net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse repoCommandResponse_ = net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse, net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.Builder, net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponseOrBuilder> repoCommandResponseBuilder_;
      /**
       * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
       *
       * <pre>
       * A RepoCommandResponseMessage has one RepoCommandResponse.
       * </pre>
       */
      public boolean hasRepoCommandResponse() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
       *
       * <pre>
       * A RepoCommandResponseMessage has one RepoCommandResponse.
       * </pre>
       */
      public net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse getRepoCommandResponse() {
        if (repoCommandResponseBuilder_ == null) {
          return repoCommandResponse_;
        } else {
          return repoCommandResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
       *
       * <pre>
       * A RepoCommandResponseMessage has one RepoCommandResponse.
       * </pre>
       */
      public Builder setRepoCommandResponse(net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse value) {
        if (repoCommandResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          repoCommandResponse_ = value;
          onChanged();
        } else {
          repoCommandResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
       *
       * <pre>
       * A RepoCommandResponseMessage has one RepoCommandResponse.
       * </pre>
       */
      public Builder setRepoCommandResponse(
          net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.Builder builderForValue) {
        if (repoCommandResponseBuilder_ == null) {
          repoCommandResponse_ = builderForValue.build();
          onChanged();
        } else {
          repoCommandResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
       *
       * <pre>
       * A RepoCommandResponseMessage has one RepoCommandResponse.
       * </pre>
       */
      public Builder mergeRepoCommandResponse(net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse value) {
        if (repoCommandResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              repoCommandResponse_ != net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.getDefaultInstance()) {
            repoCommandResponse_ =
              net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.newBuilder(repoCommandResponse_).mergeFrom(value).buildPartial();
          } else {
            repoCommandResponse_ = value;
          }
          onChanged();
        } else {
          repoCommandResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
       *
       * <pre>
       * A RepoCommandResponseMessage has one RepoCommandResponse.
       * </pre>
       */
      public Builder clearRepoCommandResponse() {
        if (repoCommandResponseBuilder_ == null) {
          repoCommandResponse_ = net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.getDefaultInstance();
          onChanged();
        } else {
          repoCommandResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
       *
       * <pre>
       * A RepoCommandResponseMessage has one RepoCommandResponse.
       * </pre>
       */
      public net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.Builder getRepoCommandResponseBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRepoCommandResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
       *
       * <pre>
       * A RepoCommandResponseMessage has one RepoCommandResponse.
       * </pre>
       */
      public net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponseOrBuilder getRepoCommandResponseOrBuilder() {
        if (repoCommandResponseBuilder_ != null) {
          return repoCommandResponseBuilder_.getMessageOrBuilder();
        } else {
          return repoCommandResponse_;
        }
      }
      /**
       * <code>required .net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage.RepoCommandResponse repo_command_response = 207;</code>
       *
       * <pre>
       * A RepoCommandResponseMessage has one RepoCommandResponse.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse, net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.Builder, net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponseOrBuilder> 
          getRepoCommandResponseFieldBuilder() {
        if (repoCommandResponseBuilder_ == null) {
          repoCommandResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse, net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponse.Builder, net.named_data.jndn.tests.repo_ng.RepoCommandResponseProto.RepoCommandResponseMessage.RepoCommandResponseOrBuilder>(
                  repoCommandResponse_,
                  getParentForChildren(),
                  isClean());
          repoCommandResponse_ = null;
        }
        return repoCommandResponseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage)
    }

    static {
      defaultInstance = new RepoCommandResponseMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.named_data.jndn.tests.repo_ng.RepoCommandResponseMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_RepoCommandResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_RepoCommandResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!repo-command-response-proto.proto\022!net" +
      ".named_data.jndn.tests.repo_ng\"\254\002\n\032RepoC" +
      "ommandResponseMessage\022q\n\025repo_command_re" +
      "sponse\030\317\001 \002(\0132Q.net.named_data.jndn.test" +
      "s.repo_ng.RepoCommandResponseMessage.Rep" +
      "oCommandResponse\032\232\001\n\023RepoCommandResponse" +
      "\022\023\n\nprocess_id\030\316\001 \001(\004\022\024\n\013status_code\030\320\001 " +
      "\002(\004\022\027\n\016start_block_id\030\314\001 \001(\004\022\025\n\014end_bloc" +
      "k_id\030\315\001 \001(\004\022\023\n\ninsert_num\030\321\001 \001(\004\022\023\n\ndele" +
      "te_num\030\322\001 \001(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_descriptor,
              new java.lang.String[] { "RepoCommandResponse", });
          internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_RepoCommandResponse_descriptor =
            internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_descriptor.getNestedTypes().get(0);
          internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_RepoCommandResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_named_data_jndn_tests_repo_ng_RepoCommandResponseMessage_RepoCommandResponse_descriptor,
              new java.lang.String[] { "ProcessId", "StatusCode", "StartBlockId", "EndBlockId", "InsertNum", "DeleteNum", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
