// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel-status-proto.proto

package net.named_data.jndn.tests;

public final class ChannelStatusProto {
  private ChannelStatusProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChannelStatusMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;
    /**
     * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
     *
     * <pre>
     * A ChannelStatusMessage has repeated ChannelStatus.
     * </pre>
     */
    java.util.List<net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus> 
        getChannelStatusList();
    /**
     * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
     *
     * <pre>
     * A ChannelStatusMessage has repeated ChannelStatus.
     * </pre>
     */
    net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus getChannelStatus(int index);
    /**
     * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
     *
     * <pre>
     * A ChannelStatusMessage has repeated ChannelStatus.
     * </pre>
     */
    int getChannelStatusCount();
    /**
     * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
     *
     * <pre>
     * A ChannelStatusMessage has repeated ChannelStatus.
     * </pre>
     */
    java.util.List<? extends net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatusOrBuilder> 
        getChannelStatusOrBuilderList();
    /**
     * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
     *
     * <pre>
     * A ChannelStatusMessage has repeated ChannelStatus.
     * </pre>
     */
    net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatusOrBuilder getChannelStatusOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code net.named_data.jndn.tests.ChannelStatusMessage}
   *
   * <pre>
   * Protobuf has no "outer" message type, so we need to put the TLV ChannelStatus
   * message inside an outer "typeless" ChannelStatusMessage.
   * </pre>
   */
  public static final class ChannelStatusMessage extends
      com.google.protobuf.GeneratedMessage
      implements ChannelStatusMessageOrBuilder {
    // Use ChannelStatusMessage.newBuilder() to construct.
    private ChannelStatusMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChannelStatusMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChannelStatusMessage defaultInstance;
    public static ChannelStatusMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ChannelStatusMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChannelStatusMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 1042: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                channelStatus_ = new java.util.ArrayList<net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus>();
                mutable_bitField0_ |= 0x00000001;
              }
              channelStatus_.add(input.readMessage(net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          channelStatus_ = java.util.Collections.unmodifiableList(channelStatus_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.named_data.jndn.tests.ChannelStatusProto.internal_static_net_named_data_jndn_tests_ChannelStatusMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.named_data.jndn.tests.ChannelStatusProto.internal_static_net_named_data_jndn_tests_ChannelStatusMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.class, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ChannelStatusMessage> PARSER =
        new com.google.protobuf.AbstractParser<ChannelStatusMessage>() {
      public ChannelStatusMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChannelStatusMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChannelStatusMessage> getParserForType() {
      return PARSER;
    }

    public interface ChannelStatusOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string local_uri = 129;
      /**
       * <code>required string local_uri = 129;</code>
       */
      boolean hasLocalUri();
      /**
       * <code>required string local_uri = 129;</code>
       */
      java.lang.String getLocalUri();
      /**
       * <code>required string local_uri = 129;</code>
       */
      com.google.protobuf.ByteString
          getLocalUriBytes();
    }
    /**
     * Protobuf type {@code net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus}
     */
    public static final class ChannelStatus extends
        com.google.protobuf.GeneratedMessage
        implements ChannelStatusOrBuilder {
      // Use ChannelStatus.newBuilder() to construct.
      private ChannelStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private ChannelStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final ChannelStatus defaultInstance;
      public static ChannelStatus getDefaultInstance() {
        return defaultInstance;
      }

      public ChannelStatus getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private ChannelStatus(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 1034: {
                bitField0_ |= 0x00000001;
                localUri_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.named_data.jndn.tests.ChannelStatusProto.internal_static_net_named_data_jndn_tests_ChannelStatusMessage_ChannelStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.named_data.jndn.tests.ChannelStatusProto.internal_static_net_named_data_jndn_tests_ChannelStatusMessage_ChannelStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.class, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.Builder.class);
      }

      public static com.google.protobuf.Parser<ChannelStatus> PARSER =
          new com.google.protobuf.AbstractParser<ChannelStatus>() {
        public ChannelStatus parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChannelStatus(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<ChannelStatus> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string local_uri = 129;
      public static final int LOCAL_URI_FIELD_NUMBER = 129;
      private java.lang.Object localUri_;
      /**
       * <code>required string local_uri = 129;</code>
       */
      public boolean hasLocalUri() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string local_uri = 129;</code>
       */
      public java.lang.String getLocalUri() {
        java.lang.Object ref = localUri_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            localUri_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string local_uri = 129;</code>
       */
      public com.google.protobuf.ByteString
          getLocalUriBytes() {
        java.lang.Object ref = localUri_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        localUri_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasLocalUri()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(129, getLocalUriBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(129, getLocalUriBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatusOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.named_data.jndn.tests.ChannelStatusProto.internal_static_net_named_data_jndn_tests_ChannelStatusMessage_ChannelStatus_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.named_data.jndn.tests.ChannelStatusProto.internal_static_net_named_data_jndn_tests_ChannelStatusMessage_ChannelStatus_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.class, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.Builder.class);
        }

        // Construct using net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          localUri_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.named_data.jndn.tests.ChannelStatusProto.internal_static_net_named_data_jndn_tests_ChannelStatusMessage_ChannelStatus_descriptor;
        }

        public net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus getDefaultInstanceForType() {
          return net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.getDefaultInstance();
        }

        public net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus build() {
          net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus buildPartial() {
          net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus result = new net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.localUri_ = localUri_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus) {
            return mergeFrom((net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus other) {
          if (other == net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.getDefaultInstance()) return this;
          if (other.hasLocalUri()) {
            bitField0_ |= 0x00000001;
            localUri_ = other.localUri_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasLocalUri()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string local_uri = 129;
        private java.lang.Object localUri_ = "";
        /**
         * <code>required string local_uri = 129;</code>
         */
        public boolean hasLocalUri() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string local_uri = 129;</code>
         */
        public java.lang.String getLocalUri() {
          java.lang.Object ref = localUri_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            localUri_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string local_uri = 129;</code>
         */
        public com.google.protobuf.ByteString
            getLocalUriBytes() {
          java.lang.Object ref = localUri_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            localUri_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string local_uri = 129;</code>
         */
        public Builder setLocalUri(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          localUri_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string local_uri = 129;</code>
         */
        public Builder clearLocalUri() {
          bitField0_ = (bitField0_ & ~0x00000001);
          localUri_ = getDefaultInstance().getLocalUri();
          onChanged();
          return this;
        }
        /**
         * <code>required string local_uri = 129;</code>
         */
        public Builder setLocalUriBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          localUri_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus)
      }

      static {
        defaultInstance = new ChannelStatus(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus)
    }

    // repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;
    public static final int CHANNEL_STATUS_FIELD_NUMBER = 130;
    private java.util.List<net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus> channelStatus_;
    /**
     * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
     *
     * <pre>
     * A ChannelStatusMessage has repeated ChannelStatus.
     * </pre>
     */
    public java.util.List<net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus> getChannelStatusList() {
      return channelStatus_;
    }
    /**
     * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
     *
     * <pre>
     * A ChannelStatusMessage has repeated ChannelStatus.
     * </pre>
     */
    public java.util.List<? extends net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatusOrBuilder> 
        getChannelStatusOrBuilderList() {
      return channelStatus_;
    }
    /**
     * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
     *
     * <pre>
     * A ChannelStatusMessage has repeated ChannelStatus.
     * </pre>
     */
    public int getChannelStatusCount() {
      return channelStatus_.size();
    }
    /**
     * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
     *
     * <pre>
     * A ChannelStatusMessage has repeated ChannelStatus.
     * </pre>
     */
    public net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus getChannelStatus(int index) {
      return channelStatus_.get(index);
    }
    /**
     * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
     *
     * <pre>
     * A ChannelStatusMessage has repeated ChannelStatus.
     * </pre>
     */
    public net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatusOrBuilder getChannelStatusOrBuilder(
        int index) {
      return channelStatus_.get(index);
    }

    private void initFields() {
      channelStatus_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getChannelStatusCount(); i++) {
        if (!getChannelStatus(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < channelStatus_.size(); i++) {
        output.writeMessage(130, channelStatus_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < channelStatus_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(130, channelStatus_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.named_data.jndn.tests.ChannelStatusMessage}
     *
     * <pre>
     * Protobuf has no "outer" message type, so we need to put the TLV ChannelStatus
     * message inside an outer "typeless" ChannelStatusMessage.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.named_data.jndn.tests.ChannelStatusProto.internal_static_net_named_data_jndn_tests_ChannelStatusMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.named_data.jndn.tests.ChannelStatusProto.internal_static_net_named_data_jndn_tests_ChannelStatusMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.class, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.Builder.class);
      }

      // Construct using net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getChannelStatusFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (channelStatusBuilder_ == null) {
          channelStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          channelStatusBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.named_data.jndn.tests.ChannelStatusProto.internal_static_net_named_data_jndn_tests_ChannelStatusMessage_descriptor;
      }

      public net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage getDefaultInstanceForType() {
        return net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.getDefaultInstance();
      }

      public net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage build() {
        net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage buildPartial() {
        net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage result = new net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage(this);
        int from_bitField0_ = bitField0_;
        if (channelStatusBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            channelStatus_ = java.util.Collections.unmodifiableList(channelStatus_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.channelStatus_ = channelStatus_;
        } else {
          result.channelStatus_ = channelStatusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage) {
          return mergeFrom((net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage other) {
        if (other == net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.getDefaultInstance()) return this;
        if (channelStatusBuilder_ == null) {
          if (!other.channelStatus_.isEmpty()) {
            if (channelStatus_.isEmpty()) {
              channelStatus_ = other.channelStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureChannelStatusIsMutable();
              channelStatus_.addAll(other.channelStatus_);
            }
            onChanged();
          }
        } else {
          if (!other.channelStatus_.isEmpty()) {
            if (channelStatusBuilder_.isEmpty()) {
              channelStatusBuilder_.dispose();
              channelStatusBuilder_ = null;
              channelStatus_ = other.channelStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
              channelStatusBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getChannelStatusFieldBuilder() : null;
            } else {
              channelStatusBuilder_.addAllMessages(other.channelStatus_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getChannelStatusCount(); i++) {
          if (!getChannelStatus(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;
      private java.util.List<net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus> channelStatus_ =
        java.util.Collections.emptyList();
      private void ensureChannelStatusIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          channelStatus_ = new java.util.ArrayList<net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus>(channelStatus_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.Builder, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatusOrBuilder> channelStatusBuilder_;

      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public java.util.List<net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus> getChannelStatusList() {
        if (channelStatusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(channelStatus_);
        } else {
          return channelStatusBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public int getChannelStatusCount() {
        if (channelStatusBuilder_ == null) {
          return channelStatus_.size();
        } else {
          return channelStatusBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus getChannelStatus(int index) {
        if (channelStatusBuilder_ == null) {
          return channelStatus_.get(index);
        } else {
          return channelStatusBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public Builder setChannelStatus(
          int index, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus value) {
        if (channelStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChannelStatusIsMutable();
          channelStatus_.set(index, value);
          onChanged();
        } else {
          channelStatusBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public Builder setChannelStatus(
          int index, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.Builder builderForValue) {
        if (channelStatusBuilder_ == null) {
          ensureChannelStatusIsMutable();
          channelStatus_.set(index, builderForValue.build());
          onChanged();
        } else {
          channelStatusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public Builder addChannelStatus(net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus value) {
        if (channelStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChannelStatusIsMutable();
          channelStatus_.add(value);
          onChanged();
        } else {
          channelStatusBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public Builder addChannelStatus(
          int index, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus value) {
        if (channelStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChannelStatusIsMutable();
          channelStatus_.add(index, value);
          onChanged();
        } else {
          channelStatusBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public Builder addChannelStatus(
          net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.Builder builderForValue) {
        if (channelStatusBuilder_ == null) {
          ensureChannelStatusIsMutable();
          channelStatus_.add(builderForValue.build());
          onChanged();
        } else {
          channelStatusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public Builder addChannelStatus(
          int index, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.Builder builderForValue) {
        if (channelStatusBuilder_ == null) {
          ensureChannelStatusIsMutable();
          channelStatus_.add(index, builderForValue.build());
          onChanged();
        } else {
          channelStatusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public Builder addAllChannelStatus(
          java.lang.Iterable<? extends net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus> values) {
        if (channelStatusBuilder_ == null) {
          ensureChannelStatusIsMutable();
          super.addAll(values, channelStatus_);
          onChanged();
        } else {
          channelStatusBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public Builder clearChannelStatus() {
        if (channelStatusBuilder_ == null) {
          channelStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          channelStatusBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public Builder removeChannelStatus(int index) {
        if (channelStatusBuilder_ == null) {
          ensureChannelStatusIsMutable();
          channelStatus_.remove(index);
          onChanged();
        } else {
          channelStatusBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.Builder getChannelStatusBuilder(
          int index) {
        return getChannelStatusFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatusOrBuilder getChannelStatusOrBuilder(
          int index) {
        if (channelStatusBuilder_ == null) {
          return channelStatus_.get(index);  } else {
          return channelStatusBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public java.util.List<? extends net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatusOrBuilder> 
           getChannelStatusOrBuilderList() {
        if (channelStatusBuilder_ != null) {
          return channelStatusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(channelStatus_);
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.Builder addChannelStatusBuilder() {
        return getChannelStatusFieldBuilder().addBuilder(
            net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.Builder addChannelStatusBuilder(
          int index) {
        return getChannelStatusFieldBuilder().addBuilder(
            index, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.ChannelStatusMessage.ChannelStatus channel_status = 130;</code>
       *
       * <pre>
       * A ChannelStatusMessage has repeated ChannelStatus.
       * </pre>
       */
      public java.util.List<net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.Builder> 
           getChannelStatusBuilderList() {
        return getChannelStatusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.Builder, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatusOrBuilder> 
          getChannelStatusFieldBuilder() {
        if (channelStatusBuilder_ == null) {
          channelStatusBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatus.Builder, net.named_data.jndn.tests.ChannelStatusProto.ChannelStatusMessage.ChannelStatusOrBuilder>(
                  channelStatus_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          channelStatus_ = null;
        }
        return channelStatusBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:net.named_data.jndn.tests.ChannelStatusMessage)
    }

    static {
      defaultInstance = new ChannelStatusMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.named_data.jndn.tests.ChannelStatusMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_named_data_jndn_tests_ChannelStatusMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_named_data_jndn_tests_ChannelStatusMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_named_data_jndn_tests_ChannelStatusMessage_ChannelStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_named_data_jndn_tests_ChannelStatusMessage_ChannelStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032channel-status-proto.proto\022\031net.named_" +
      "data.jndn.tests\"\223\001\n\024ChannelStatusMessage" +
      "\022V\n\016channel_status\030\202\001 \003(\0132=.net.named_da" +
      "ta.jndn.tests.ChannelStatusMessage.Chann" +
      "elStatus\032#\n\rChannelStatus\022\022\n\tlocal_uri\030\201" +
      "\001 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_named_data_jndn_tests_ChannelStatusMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_named_data_jndn_tests_ChannelStatusMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_named_data_jndn_tests_ChannelStatusMessage_descriptor,
              new java.lang.String[] { "ChannelStatus", });
          internal_static_net_named_data_jndn_tests_ChannelStatusMessage_ChannelStatus_descriptor =
            internal_static_net_named_data_jndn_tests_ChannelStatusMessage_descriptor.getNestedTypes().get(0);
          internal_static_net_named_data_jndn_tests_ChannelStatusMessage_ChannelStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_named_data_jndn_tests_ChannelStatusMessage_ChannelStatus_descriptor,
              new java.lang.String[] { "LocalUri", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
