// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: face-status-proto.proto

package net.named_data.jndn.tests;

public final class FaceStatusProto {
  private FaceStatusProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FaceStatusMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:net.named_data.jndn.tests.FaceStatusMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
     *
     * <pre>
     * A FaceStatusMessage has repeated FaceStatus.
     * </pre>
     */
    java.util.List<net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus> 
        getFaceStatusList();
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
     *
     * <pre>
     * A FaceStatusMessage has repeated FaceStatus.
     * </pre>
     */
    net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus getFaceStatus(int index);
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
     *
     * <pre>
     * A FaceStatusMessage has repeated FaceStatus.
     * </pre>
     */
    int getFaceStatusCount();
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
     *
     * <pre>
     * A FaceStatusMessage has repeated FaceStatus.
     * </pre>
     */
    java.util.List<? extends net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatusOrBuilder> 
        getFaceStatusOrBuilderList();
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
     *
     * <pre>
     * A FaceStatusMessage has repeated FaceStatus.
     * </pre>
     */
    net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatusOrBuilder getFaceStatusOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code net.named_data.jndn.tests.FaceStatusMessage}
   *
   * <pre>
   * Protobuf has no "outer" message type, so we need to put the TLV FaceStatus
   * message inside an outer "typeless" FaceStatusMessage.
   * </pre>
   */
  public static final class FaceStatusMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:net.named_data.jndn.tests.FaceStatusMessage)
      FaceStatusMessageOrBuilder {
    // Use FaceStatusMessage.newBuilder() to construct.
    private FaceStatusMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FaceStatusMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FaceStatusMessage defaultInstance;
    public static FaceStatusMessage getDefaultInstance() {
      return defaultInstance;
    }

    public FaceStatusMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FaceStatusMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 1026: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                faceStatus_ = new java.util.ArrayList<net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus>();
                mutable_bitField0_ |= 0x00000001;
              }
              faceStatus_.add(input.readMessage(net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          faceStatus_ = java.util.Collections.unmodifiableList(faceStatus_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.named_data.jndn.tests.FaceStatusProto.internal_static_net_named_data_jndn_tests_FaceStatusMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.named_data.jndn.tests.FaceStatusProto.internal_static_net_named_data_jndn_tests_FaceStatusMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.class, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<FaceStatusMessage> PARSER =
        new com.google.protobuf.AbstractParser<FaceStatusMessage>() {
      public FaceStatusMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FaceStatusMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FaceStatusMessage> getParserForType() {
      return PARSER;
    }

    public interface FaceStatusOrBuilder extends
        // @@protoc_insertion_point(interface_extends:net.named_data.jndn.tests.FaceStatusMessage.FaceStatus)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required uint64 face_id = 105;</code>
       */
      boolean hasFaceId();
      /**
       * <code>required uint64 face_id = 105;</code>
       */
      long getFaceId();

      /**
       * <code>required string uri = 114;</code>
       */
      boolean hasUri();
      /**
       * <code>required string uri = 114;</code>
       */
      java.lang.String getUri();
      /**
       * <code>required string uri = 114;</code>
       */
      com.google.protobuf.ByteString
          getUriBytes();

      /**
       * <code>required string local_uri = 129;</code>
       */
      boolean hasLocalUri();
      /**
       * <code>required string local_uri = 129;</code>
       */
      java.lang.String getLocalUri();
      /**
       * <code>required string local_uri = 129;</code>
       */
      com.google.protobuf.ByteString
          getLocalUriBytes();

      /**
       * <code>optional uint64 expiration_period = 109;</code>
       */
      boolean hasExpirationPeriod();
      /**
       * <code>optional uint64 expiration_period = 109;</code>
       */
      long getExpirationPeriod();

      /**
       * <code>required uint64 face_scope = 132;</code>
       */
      boolean hasFaceScope();
      /**
       * <code>required uint64 face_scope = 132;</code>
       */
      long getFaceScope();

      /**
       * <code>required uint64 face_persistency = 133;</code>
       */
      boolean hasFacePersistency();
      /**
       * <code>required uint64 face_persistency = 133;</code>
       */
      long getFacePersistency();

      /**
       * <code>required uint64 link_type = 134;</code>
       */
      boolean hasLinkType();
      /**
       * <code>required uint64 link_type = 134;</code>
       */
      long getLinkType();

      /**
       * <code>required uint64 n_in_interests = 144;</code>
       */
      boolean hasNInInterests();
      /**
       * <code>required uint64 n_in_interests = 144;</code>
       */
      long getNInInterests();

      /**
       * <code>required uint64 n_in_datas = 145;</code>
       */
      boolean hasNInDatas();
      /**
       * <code>required uint64 n_in_datas = 145;</code>
       */
      long getNInDatas();

      /**
       * <code>required uint64 n_in_nacks = 151;</code>
       */
      boolean hasNInNacks();
      /**
       * <code>required uint64 n_in_nacks = 151;</code>
       */
      long getNInNacks();

      /**
       * <code>required uint64 n_out_interests = 146;</code>
       */
      boolean hasNOutInterests();
      /**
       * <code>required uint64 n_out_interests = 146;</code>
       */
      long getNOutInterests();

      /**
       * <code>required uint64 n_out_datas = 147;</code>
       */
      boolean hasNOutDatas();
      /**
       * <code>required uint64 n_out_datas = 147;</code>
       */
      long getNOutDatas();

      /**
       * <code>required uint64 n_out_nacks = 152;</code>
       */
      boolean hasNOutNacks();
      /**
       * <code>required uint64 n_out_nacks = 152;</code>
       */
      long getNOutNacks();

      /**
       * <code>required uint64 n_in_bytes = 148;</code>
       */
      boolean hasNInBytes();
      /**
       * <code>required uint64 n_in_bytes = 148;</code>
       */
      long getNInBytes();

      /**
       * <code>required uint64 n_out_bytes = 149;</code>
       */
      boolean hasNOutBytes();
      /**
       * <code>required uint64 n_out_bytes = 149;</code>
       */
      long getNOutBytes();
    }
    /**
     * Protobuf type {@code net.named_data.jndn.tests.FaceStatusMessage.FaceStatus}
     */
    public static final class FaceStatus extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:net.named_data.jndn.tests.FaceStatusMessage.FaceStatus)
        FaceStatusOrBuilder {
      // Use FaceStatus.newBuilder() to construct.
      private FaceStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private FaceStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final FaceStatus defaultInstance;
      public static FaceStatus getDefaultInstance() {
        return defaultInstance;
      }

      public FaceStatus getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private FaceStatus(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 840: {
                bitField0_ |= 0x00000001;
                faceId_ = input.readUInt64();
                break;
              }
              case 872: {
                bitField0_ |= 0x00000008;
                expirationPeriod_ = input.readUInt64();
                break;
              }
              case 914: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                uri_ = bs;
                break;
              }
              case 1034: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                localUri_ = bs;
                break;
              }
              case 1056: {
                bitField0_ |= 0x00000010;
                faceScope_ = input.readUInt64();
                break;
              }
              case 1064: {
                bitField0_ |= 0x00000020;
                facePersistency_ = input.readUInt64();
                break;
              }
              case 1072: {
                bitField0_ |= 0x00000040;
                linkType_ = input.readUInt64();
                break;
              }
              case 1152: {
                bitField0_ |= 0x00000080;
                nInInterests_ = input.readUInt64();
                break;
              }
              case 1160: {
                bitField0_ |= 0x00000100;
                nInDatas_ = input.readUInt64();
                break;
              }
              case 1168: {
                bitField0_ |= 0x00000400;
                nOutInterests_ = input.readUInt64();
                break;
              }
              case 1176: {
                bitField0_ |= 0x00000800;
                nOutDatas_ = input.readUInt64();
                break;
              }
              case 1184: {
                bitField0_ |= 0x00002000;
                nInBytes_ = input.readUInt64();
                break;
              }
              case 1192: {
                bitField0_ |= 0x00004000;
                nOutBytes_ = input.readUInt64();
                break;
              }
              case 1208: {
                bitField0_ |= 0x00000200;
                nInNacks_ = input.readUInt64();
                break;
              }
              case 1216: {
                bitField0_ |= 0x00001000;
                nOutNacks_ = input.readUInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.named_data.jndn.tests.FaceStatusProto.internal_static_net_named_data_jndn_tests_FaceStatusMessage_FaceStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.named_data.jndn.tests.FaceStatusProto.internal_static_net_named_data_jndn_tests_FaceStatusMessage_FaceStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.class, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.Builder.class);
      }

      public static com.google.protobuf.Parser<FaceStatus> PARSER =
          new com.google.protobuf.AbstractParser<FaceStatus>() {
        public FaceStatus parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new FaceStatus(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<FaceStatus> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int FACE_ID_FIELD_NUMBER = 105;
      private long faceId_;
      /**
       * <code>required uint64 face_id = 105;</code>
       */
      public boolean hasFaceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 face_id = 105;</code>
       */
      public long getFaceId() {
        return faceId_;
      }

      public static final int URI_FIELD_NUMBER = 114;
      private java.lang.Object uri_;
      /**
       * <code>required string uri = 114;</code>
       */
      public boolean hasUri() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string uri = 114;</code>
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uri_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string uri = 114;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int LOCAL_URI_FIELD_NUMBER = 129;
      private java.lang.Object localUri_;
      /**
       * <code>required string local_uri = 129;</code>
       */
      public boolean hasLocalUri() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string local_uri = 129;</code>
       */
      public java.lang.String getLocalUri() {
        java.lang.Object ref = localUri_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            localUri_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string local_uri = 129;</code>
       */
      public com.google.protobuf.ByteString
          getLocalUriBytes() {
        java.lang.Object ref = localUri_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int EXPIRATION_PERIOD_FIELD_NUMBER = 109;
      private long expirationPeriod_;
      /**
       * <code>optional uint64 expiration_period = 109;</code>
       */
      public boolean hasExpirationPeriod() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 expiration_period = 109;</code>
       */
      public long getExpirationPeriod() {
        return expirationPeriod_;
      }

      public static final int FACE_SCOPE_FIELD_NUMBER = 132;
      private long faceScope_;
      /**
       * <code>required uint64 face_scope = 132;</code>
       */
      public boolean hasFaceScope() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint64 face_scope = 132;</code>
       */
      public long getFaceScope() {
        return faceScope_;
      }

      public static final int FACE_PERSISTENCY_FIELD_NUMBER = 133;
      private long facePersistency_;
      /**
       * <code>required uint64 face_persistency = 133;</code>
       */
      public boolean hasFacePersistency() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required uint64 face_persistency = 133;</code>
       */
      public long getFacePersistency() {
        return facePersistency_;
      }

      public static final int LINK_TYPE_FIELD_NUMBER = 134;
      private long linkType_;
      /**
       * <code>required uint64 link_type = 134;</code>
       */
      public boolean hasLinkType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required uint64 link_type = 134;</code>
       */
      public long getLinkType() {
        return linkType_;
      }

      public static final int N_IN_INTERESTS_FIELD_NUMBER = 144;
      private long nInInterests_;
      /**
       * <code>required uint64 n_in_interests = 144;</code>
       */
      public boolean hasNInInterests() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required uint64 n_in_interests = 144;</code>
       */
      public long getNInInterests() {
        return nInInterests_;
      }

      public static final int N_IN_DATAS_FIELD_NUMBER = 145;
      private long nInDatas_;
      /**
       * <code>required uint64 n_in_datas = 145;</code>
       */
      public boolean hasNInDatas() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required uint64 n_in_datas = 145;</code>
       */
      public long getNInDatas() {
        return nInDatas_;
      }

      public static final int N_IN_NACKS_FIELD_NUMBER = 151;
      private long nInNacks_;
      /**
       * <code>required uint64 n_in_nacks = 151;</code>
       */
      public boolean hasNInNacks() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required uint64 n_in_nacks = 151;</code>
       */
      public long getNInNacks() {
        return nInNacks_;
      }

      public static final int N_OUT_INTERESTS_FIELD_NUMBER = 146;
      private long nOutInterests_;
      /**
       * <code>required uint64 n_out_interests = 146;</code>
       */
      public boolean hasNOutInterests() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required uint64 n_out_interests = 146;</code>
       */
      public long getNOutInterests() {
        return nOutInterests_;
      }

      public static final int N_OUT_DATAS_FIELD_NUMBER = 147;
      private long nOutDatas_;
      /**
       * <code>required uint64 n_out_datas = 147;</code>
       */
      public boolean hasNOutDatas() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required uint64 n_out_datas = 147;</code>
       */
      public long getNOutDatas() {
        return nOutDatas_;
      }

      public static final int N_OUT_NACKS_FIELD_NUMBER = 152;
      private long nOutNacks_;
      /**
       * <code>required uint64 n_out_nacks = 152;</code>
       */
      public boolean hasNOutNacks() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required uint64 n_out_nacks = 152;</code>
       */
      public long getNOutNacks() {
        return nOutNacks_;
      }

      public static final int N_IN_BYTES_FIELD_NUMBER = 148;
      private long nInBytes_;
      /**
       * <code>required uint64 n_in_bytes = 148;</code>
       */
      public boolean hasNInBytes() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required uint64 n_in_bytes = 148;</code>
       */
      public long getNInBytes() {
        return nInBytes_;
      }

      public static final int N_OUT_BYTES_FIELD_NUMBER = 149;
      private long nOutBytes_;
      /**
       * <code>required uint64 n_out_bytes = 149;</code>
       */
      public boolean hasNOutBytes() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>required uint64 n_out_bytes = 149;</code>
       */
      public long getNOutBytes() {
        return nOutBytes_;
      }

      private void initFields() {
        faceId_ = 0L;
        uri_ = "";
        localUri_ = "";
        expirationPeriod_ = 0L;
        faceScope_ = 0L;
        facePersistency_ = 0L;
        linkType_ = 0L;
        nInInterests_ = 0L;
        nInDatas_ = 0L;
        nInNacks_ = 0L;
        nOutInterests_ = 0L;
        nOutDatas_ = 0L;
        nOutNacks_ = 0L;
        nInBytes_ = 0L;
        nOutBytes_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasFaceId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasUri()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLocalUri()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasFaceScope()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasFacePersistency()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLinkType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasNInInterests()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasNInDatas()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasNInNacks()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasNOutInterests()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasNOutDatas()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasNOutNacks()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasNInBytes()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasNOutBytes()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt64(105, faceId_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeUInt64(109, expirationPeriod_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(114, getUriBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(129, getLocalUriBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeUInt64(132, faceScope_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeUInt64(133, facePersistency_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeUInt64(134, linkType_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          output.writeUInt64(144, nInInterests_);
        }
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          output.writeUInt64(145, nInDatas_);
        }
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          output.writeUInt64(146, nOutInterests_);
        }
        if (((bitField0_ & 0x00000800) == 0x00000800)) {
          output.writeUInt64(147, nOutDatas_);
        }
        if (((bitField0_ & 0x00002000) == 0x00002000)) {
          output.writeUInt64(148, nInBytes_);
        }
        if (((bitField0_ & 0x00004000) == 0x00004000)) {
          output.writeUInt64(149, nOutBytes_);
        }
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          output.writeUInt64(151, nInNacks_);
        }
        if (((bitField0_ & 0x00001000) == 0x00001000)) {
          output.writeUInt64(152, nOutNacks_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(105, faceId_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(109, expirationPeriod_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(114, getUriBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(129, getLocalUriBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(132, faceScope_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(133, facePersistency_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(134, linkType_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(144, nInInterests_);
        }
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(145, nInDatas_);
        }
        if (((bitField0_ & 0x00000400) == 0x00000400)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(146, nOutInterests_);
        }
        if (((bitField0_ & 0x00000800) == 0x00000800)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(147, nOutDatas_);
        }
        if (((bitField0_ & 0x00002000) == 0x00002000)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(148, nInBytes_);
        }
        if (((bitField0_ & 0x00004000) == 0x00004000)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(149, nOutBytes_);
        }
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(151, nInNacks_);
        }
        if (((bitField0_ & 0x00001000) == 0x00001000)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(152, nOutNacks_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code net.named_data.jndn.tests.FaceStatusMessage.FaceStatus}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:net.named_data.jndn.tests.FaceStatusMessage.FaceStatus)
          net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatusOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.named_data.jndn.tests.FaceStatusProto.internal_static_net_named_data_jndn_tests_FaceStatusMessage_FaceStatus_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.named_data.jndn.tests.FaceStatusProto.internal_static_net_named_data_jndn_tests_FaceStatusMessage_FaceStatus_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.class, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.Builder.class);
        }

        // Construct using net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          faceId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          uri_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          localUri_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          expirationPeriod_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000008);
          faceScope_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000010);
          facePersistency_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000020);
          linkType_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000040);
          nInInterests_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000080);
          nInDatas_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000100);
          nInNacks_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000200);
          nOutInterests_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000400);
          nOutDatas_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000800);
          nOutNacks_ = 0L;
          bitField0_ = (bitField0_ & ~0x00001000);
          nInBytes_ = 0L;
          bitField0_ = (bitField0_ & ~0x00002000);
          nOutBytes_ = 0L;
          bitField0_ = (bitField0_ & ~0x00004000);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.named_data.jndn.tests.FaceStatusProto.internal_static_net_named_data_jndn_tests_FaceStatusMessage_FaceStatus_descriptor;
        }

        public net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus getDefaultInstanceForType() {
          return net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.getDefaultInstance();
        }

        public net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus build() {
          net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus buildPartial() {
          net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus result = new net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.faceId_ = faceId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.uri_ = uri_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.localUri_ = localUri_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.expirationPeriod_ = expirationPeriod_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.faceScope_ = faceScope_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.facePersistency_ = facePersistency_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.linkType_ = linkType_;
          if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
            to_bitField0_ |= 0x00000080;
          }
          result.nInInterests_ = nInInterests_;
          if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
            to_bitField0_ |= 0x00000100;
          }
          result.nInDatas_ = nInDatas_;
          if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
            to_bitField0_ |= 0x00000200;
          }
          result.nInNacks_ = nInNacks_;
          if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
            to_bitField0_ |= 0x00000400;
          }
          result.nOutInterests_ = nOutInterests_;
          if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
            to_bitField0_ |= 0x00000800;
          }
          result.nOutDatas_ = nOutDatas_;
          if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
            to_bitField0_ |= 0x00001000;
          }
          result.nOutNacks_ = nOutNacks_;
          if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
            to_bitField0_ |= 0x00002000;
          }
          result.nInBytes_ = nInBytes_;
          if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
            to_bitField0_ |= 0x00004000;
          }
          result.nOutBytes_ = nOutBytes_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus) {
            return mergeFrom((net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus other) {
          if (other == net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.getDefaultInstance()) return this;
          if (other.hasFaceId()) {
            setFaceId(other.getFaceId());
          }
          if (other.hasUri()) {
            bitField0_ |= 0x00000002;
            uri_ = other.uri_;
            onChanged();
          }
          if (other.hasLocalUri()) {
            bitField0_ |= 0x00000004;
            localUri_ = other.localUri_;
            onChanged();
          }
          if (other.hasExpirationPeriod()) {
            setExpirationPeriod(other.getExpirationPeriod());
          }
          if (other.hasFaceScope()) {
            setFaceScope(other.getFaceScope());
          }
          if (other.hasFacePersistency()) {
            setFacePersistency(other.getFacePersistency());
          }
          if (other.hasLinkType()) {
            setLinkType(other.getLinkType());
          }
          if (other.hasNInInterests()) {
            setNInInterests(other.getNInInterests());
          }
          if (other.hasNInDatas()) {
            setNInDatas(other.getNInDatas());
          }
          if (other.hasNInNacks()) {
            setNInNacks(other.getNInNacks());
          }
          if (other.hasNOutInterests()) {
            setNOutInterests(other.getNOutInterests());
          }
          if (other.hasNOutDatas()) {
            setNOutDatas(other.getNOutDatas());
          }
          if (other.hasNOutNacks()) {
            setNOutNacks(other.getNOutNacks());
          }
          if (other.hasNInBytes()) {
            setNInBytes(other.getNInBytes());
          }
          if (other.hasNOutBytes()) {
            setNOutBytes(other.getNOutBytes());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasFaceId()) {
            
            return false;
          }
          if (!hasUri()) {
            
            return false;
          }
          if (!hasLocalUri()) {
            
            return false;
          }
          if (!hasFaceScope()) {
            
            return false;
          }
          if (!hasFacePersistency()) {
            
            return false;
          }
          if (!hasLinkType()) {
            
            return false;
          }
          if (!hasNInInterests()) {
            
            return false;
          }
          if (!hasNInDatas()) {
            
            return false;
          }
          if (!hasNInNacks()) {
            
            return false;
          }
          if (!hasNOutInterests()) {
            
            return false;
          }
          if (!hasNOutDatas()) {
            
            return false;
          }
          if (!hasNOutNacks()) {
            
            return false;
          }
          if (!hasNInBytes()) {
            
            return false;
          }
          if (!hasNOutBytes()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private long faceId_ ;
        /**
         * <code>required uint64 face_id = 105;</code>
         */
        public boolean hasFaceId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required uint64 face_id = 105;</code>
         */
        public long getFaceId() {
          return faceId_;
        }
        /**
         * <code>required uint64 face_id = 105;</code>
         */
        public Builder setFaceId(long value) {
          bitField0_ |= 0x00000001;
          faceId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 face_id = 105;</code>
         */
        public Builder clearFaceId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          faceId_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object uri_ = "";
        /**
         * <code>required string uri = 114;</code>
         */
        public boolean hasUri() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string uri = 114;</code>
         */
        public java.lang.String getUri() {
          java.lang.Object ref = uri_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              uri_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string uri = 114;</code>
         */
        public com.google.protobuf.ByteString
            getUriBytes() {
          java.lang.Object ref = uri_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            uri_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string uri = 114;</code>
         */
        public Builder setUri(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          uri_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string uri = 114;</code>
         */
        public Builder clearUri() {
          bitField0_ = (bitField0_ & ~0x00000002);
          uri_ = getDefaultInstance().getUri();
          onChanged();
          return this;
        }
        /**
         * <code>required string uri = 114;</code>
         */
        public Builder setUriBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          uri_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object localUri_ = "";
        /**
         * <code>required string local_uri = 129;</code>
         */
        public boolean hasLocalUri() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string local_uri = 129;</code>
         */
        public java.lang.String getLocalUri() {
          java.lang.Object ref = localUri_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              localUri_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string local_uri = 129;</code>
         */
        public com.google.protobuf.ByteString
            getLocalUriBytes() {
          java.lang.Object ref = localUri_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            localUri_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string local_uri = 129;</code>
         */
        public Builder setLocalUri(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          localUri_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string local_uri = 129;</code>
         */
        public Builder clearLocalUri() {
          bitField0_ = (bitField0_ & ~0x00000004);
          localUri_ = getDefaultInstance().getLocalUri();
          onChanged();
          return this;
        }
        /**
         * <code>required string local_uri = 129;</code>
         */
        public Builder setLocalUriBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          localUri_ = value;
          onChanged();
          return this;
        }

        private long expirationPeriod_ ;
        /**
         * <code>optional uint64 expiration_period = 109;</code>
         */
        public boolean hasExpirationPeriod() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional uint64 expiration_period = 109;</code>
         */
        public long getExpirationPeriod() {
          return expirationPeriod_;
        }
        /**
         * <code>optional uint64 expiration_period = 109;</code>
         */
        public Builder setExpirationPeriod(long value) {
          bitField0_ |= 0x00000008;
          expirationPeriod_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint64 expiration_period = 109;</code>
         */
        public Builder clearExpirationPeriod() {
          bitField0_ = (bitField0_ & ~0x00000008);
          expirationPeriod_ = 0L;
          onChanged();
          return this;
        }

        private long faceScope_ ;
        /**
         * <code>required uint64 face_scope = 132;</code>
         */
        public boolean hasFaceScope() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required uint64 face_scope = 132;</code>
         */
        public long getFaceScope() {
          return faceScope_;
        }
        /**
         * <code>required uint64 face_scope = 132;</code>
         */
        public Builder setFaceScope(long value) {
          bitField0_ |= 0x00000010;
          faceScope_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 face_scope = 132;</code>
         */
        public Builder clearFaceScope() {
          bitField0_ = (bitField0_ & ~0x00000010);
          faceScope_ = 0L;
          onChanged();
          return this;
        }

        private long facePersistency_ ;
        /**
         * <code>required uint64 face_persistency = 133;</code>
         */
        public boolean hasFacePersistency() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>required uint64 face_persistency = 133;</code>
         */
        public long getFacePersistency() {
          return facePersistency_;
        }
        /**
         * <code>required uint64 face_persistency = 133;</code>
         */
        public Builder setFacePersistency(long value) {
          bitField0_ |= 0x00000020;
          facePersistency_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 face_persistency = 133;</code>
         */
        public Builder clearFacePersistency() {
          bitField0_ = (bitField0_ & ~0x00000020);
          facePersistency_ = 0L;
          onChanged();
          return this;
        }

        private long linkType_ ;
        /**
         * <code>required uint64 link_type = 134;</code>
         */
        public boolean hasLinkType() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>required uint64 link_type = 134;</code>
         */
        public long getLinkType() {
          return linkType_;
        }
        /**
         * <code>required uint64 link_type = 134;</code>
         */
        public Builder setLinkType(long value) {
          bitField0_ |= 0x00000040;
          linkType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 link_type = 134;</code>
         */
        public Builder clearLinkType() {
          bitField0_ = (bitField0_ & ~0x00000040);
          linkType_ = 0L;
          onChanged();
          return this;
        }

        private long nInInterests_ ;
        /**
         * <code>required uint64 n_in_interests = 144;</code>
         */
        public boolean hasNInInterests() {
          return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        /**
         * <code>required uint64 n_in_interests = 144;</code>
         */
        public long getNInInterests() {
          return nInInterests_;
        }
        /**
         * <code>required uint64 n_in_interests = 144;</code>
         */
        public Builder setNInInterests(long value) {
          bitField0_ |= 0x00000080;
          nInInterests_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 n_in_interests = 144;</code>
         */
        public Builder clearNInInterests() {
          bitField0_ = (bitField0_ & ~0x00000080);
          nInInterests_ = 0L;
          onChanged();
          return this;
        }

        private long nInDatas_ ;
        /**
         * <code>required uint64 n_in_datas = 145;</code>
         */
        public boolean hasNInDatas() {
          return ((bitField0_ & 0x00000100) == 0x00000100);
        }
        /**
         * <code>required uint64 n_in_datas = 145;</code>
         */
        public long getNInDatas() {
          return nInDatas_;
        }
        /**
         * <code>required uint64 n_in_datas = 145;</code>
         */
        public Builder setNInDatas(long value) {
          bitField0_ |= 0x00000100;
          nInDatas_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 n_in_datas = 145;</code>
         */
        public Builder clearNInDatas() {
          bitField0_ = (bitField0_ & ~0x00000100);
          nInDatas_ = 0L;
          onChanged();
          return this;
        }

        private long nInNacks_ ;
        /**
         * <code>required uint64 n_in_nacks = 151;</code>
         */
        public boolean hasNInNacks() {
          return ((bitField0_ & 0x00000200) == 0x00000200);
        }
        /**
         * <code>required uint64 n_in_nacks = 151;</code>
         */
        public long getNInNacks() {
          return nInNacks_;
        }
        /**
         * <code>required uint64 n_in_nacks = 151;</code>
         */
        public Builder setNInNacks(long value) {
          bitField0_ |= 0x00000200;
          nInNacks_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 n_in_nacks = 151;</code>
         */
        public Builder clearNInNacks() {
          bitField0_ = (bitField0_ & ~0x00000200);
          nInNacks_ = 0L;
          onChanged();
          return this;
        }

        private long nOutInterests_ ;
        /**
         * <code>required uint64 n_out_interests = 146;</code>
         */
        public boolean hasNOutInterests() {
          return ((bitField0_ & 0x00000400) == 0x00000400);
        }
        /**
         * <code>required uint64 n_out_interests = 146;</code>
         */
        public long getNOutInterests() {
          return nOutInterests_;
        }
        /**
         * <code>required uint64 n_out_interests = 146;</code>
         */
        public Builder setNOutInterests(long value) {
          bitField0_ |= 0x00000400;
          nOutInterests_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 n_out_interests = 146;</code>
         */
        public Builder clearNOutInterests() {
          bitField0_ = (bitField0_ & ~0x00000400);
          nOutInterests_ = 0L;
          onChanged();
          return this;
        }

        private long nOutDatas_ ;
        /**
         * <code>required uint64 n_out_datas = 147;</code>
         */
        public boolean hasNOutDatas() {
          return ((bitField0_ & 0x00000800) == 0x00000800);
        }
        /**
         * <code>required uint64 n_out_datas = 147;</code>
         */
        public long getNOutDatas() {
          return nOutDatas_;
        }
        /**
         * <code>required uint64 n_out_datas = 147;</code>
         */
        public Builder setNOutDatas(long value) {
          bitField0_ |= 0x00000800;
          nOutDatas_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 n_out_datas = 147;</code>
         */
        public Builder clearNOutDatas() {
          bitField0_ = (bitField0_ & ~0x00000800);
          nOutDatas_ = 0L;
          onChanged();
          return this;
        }

        private long nOutNacks_ ;
        /**
         * <code>required uint64 n_out_nacks = 152;</code>
         */
        public boolean hasNOutNacks() {
          return ((bitField0_ & 0x00001000) == 0x00001000);
        }
        /**
         * <code>required uint64 n_out_nacks = 152;</code>
         */
        public long getNOutNacks() {
          return nOutNacks_;
        }
        /**
         * <code>required uint64 n_out_nacks = 152;</code>
         */
        public Builder setNOutNacks(long value) {
          bitField0_ |= 0x00001000;
          nOutNacks_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 n_out_nacks = 152;</code>
         */
        public Builder clearNOutNacks() {
          bitField0_ = (bitField0_ & ~0x00001000);
          nOutNacks_ = 0L;
          onChanged();
          return this;
        }

        private long nInBytes_ ;
        /**
         * <code>required uint64 n_in_bytes = 148;</code>
         */
        public boolean hasNInBytes() {
          return ((bitField0_ & 0x00002000) == 0x00002000);
        }
        /**
         * <code>required uint64 n_in_bytes = 148;</code>
         */
        public long getNInBytes() {
          return nInBytes_;
        }
        /**
         * <code>required uint64 n_in_bytes = 148;</code>
         */
        public Builder setNInBytes(long value) {
          bitField0_ |= 0x00002000;
          nInBytes_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 n_in_bytes = 148;</code>
         */
        public Builder clearNInBytes() {
          bitField0_ = (bitField0_ & ~0x00002000);
          nInBytes_ = 0L;
          onChanged();
          return this;
        }

        private long nOutBytes_ ;
        /**
         * <code>required uint64 n_out_bytes = 149;</code>
         */
        public boolean hasNOutBytes() {
          return ((bitField0_ & 0x00004000) == 0x00004000);
        }
        /**
         * <code>required uint64 n_out_bytes = 149;</code>
         */
        public long getNOutBytes() {
          return nOutBytes_;
        }
        /**
         * <code>required uint64 n_out_bytes = 149;</code>
         */
        public Builder setNOutBytes(long value) {
          bitField0_ |= 0x00004000;
          nOutBytes_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required uint64 n_out_bytes = 149;</code>
         */
        public Builder clearNOutBytes() {
          bitField0_ = (bitField0_ & ~0x00004000);
          nOutBytes_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:net.named_data.jndn.tests.FaceStatusMessage.FaceStatus)
      }

      static {
        defaultInstance = new FaceStatus(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:net.named_data.jndn.tests.FaceStatusMessage.FaceStatus)
    }

    public static final int FACE_STATUS_FIELD_NUMBER = 128;
    private java.util.List<net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus> faceStatus_;
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
     *
     * <pre>
     * A FaceStatusMessage has repeated FaceStatus.
     * </pre>
     */
    public java.util.List<net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus> getFaceStatusList() {
      return faceStatus_;
    }
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
     *
     * <pre>
     * A FaceStatusMessage has repeated FaceStatus.
     * </pre>
     */
    public java.util.List<? extends net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatusOrBuilder> 
        getFaceStatusOrBuilderList() {
      return faceStatus_;
    }
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
     *
     * <pre>
     * A FaceStatusMessage has repeated FaceStatus.
     * </pre>
     */
    public int getFaceStatusCount() {
      return faceStatus_.size();
    }
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
     *
     * <pre>
     * A FaceStatusMessage has repeated FaceStatus.
     * </pre>
     */
    public net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus getFaceStatus(int index) {
      return faceStatus_.get(index);
    }
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
     *
     * <pre>
     * A FaceStatusMessage has repeated FaceStatus.
     * </pre>
     */
    public net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatusOrBuilder getFaceStatusOrBuilder(
        int index) {
      return faceStatus_.get(index);
    }

    private void initFields() {
      faceStatus_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getFaceStatusCount(); i++) {
        if (!getFaceStatus(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < faceStatus_.size(); i++) {
        output.writeMessage(128, faceStatus_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < faceStatus_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(128, faceStatus_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.named_data.jndn.tests.FaceStatusMessage}
     *
     * <pre>
     * Protobuf has no "outer" message type, so we need to put the TLV FaceStatus
     * message inside an outer "typeless" FaceStatusMessage.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:net.named_data.jndn.tests.FaceStatusMessage)
        net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.named_data.jndn.tests.FaceStatusProto.internal_static_net_named_data_jndn_tests_FaceStatusMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.named_data.jndn.tests.FaceStatusProto.internal_static_net_named_data_jndn_tests_FaceStatusMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.class, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.Builder.class);
      }

      // Construct using net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFaceStatusFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (faceStatusBuilder_ == null) {
          faceStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          faceStatusBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.named_data.jndn.tests.FaceStatusProto.internal_static_net_named_data_jndn_tests_FaceStatusMessage_descriptor;
      }

      public net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage getDefaultInstanceForType() {
        return net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.getDefaultInstance();
      }

      public net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage build() {
        net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage buildPartial() {
        net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage result = new net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage(this);
        int from_bitField0_ = bitField0_;
        if (faceStatusBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            faceStatus_ = java.util.Collections.unmodifiableList(faceStatus_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.faceStatus_ = faceStatus_;
        } else {
          result.faceStatus_ = faceStatusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage) {
          return mergeFrom((net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage other) {
        if (other == net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.getDefaultInstance()) return this;
        if (faceStatusBuilder_ == null) {
          if (!other.faceStatus_.isEmpty()) {
            if (faceStatus_.isEmpty()) {
              faceStatus_ = other.faceStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFaceStatusIsMutable();
              faceStatus_.addAll(other.faceStatus_);
            }
            onChanged();
          }
        } else {
          if (!other.faceStatus_.isEmpty()) {
            if (faceStatusBuilder_.isEmpty()) {
              faceStatusBuilder_.dispose();
              faceStatusBuilder_ = null;
              faceStatus_ = other.faceStatus_;
              bitField0_ = (bitField0_ & ~0x00000001);
              faceStatusBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFaceStatusFieldBuilder() : null;
            } else {
              faceStatusBuilder_.addAllMessages(other.faceStatus_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getFaceStatusCount(); i++) {
          if (!getFaceStatus(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus> faceStatus_ =
        java.util.Collections.emptyList();
      private void ensureFaceStatusIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          faceStatus_ = new java.util.ArrayList<net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus>(faceStatus_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.Builder, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatusOrBuilder> faceStatusBuilder_;

      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public java.util.List<net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus> getFaceStatusList() {
        if (faceStatusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(faceStatus_);
        } else {
          return faceStatusBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public int getFaceStatusCount() {
        if (faceStatusBuilder_ == null) {
          return faceStatus_.size();
        } else {
          return faceStatusBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus getFaceStatus(int index) {
        if (faceStatusBuilder_ == null) {
          return faceStatus_.get(index);
        } else {
          return faceStatusBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public Builder setFaceStatus(
          int index, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus value) {
        if (faceStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFaceStatusIsMutable();
          faceStatus_.set(index, value);
          onChanged();
        } else {
          faceStatusBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public Builder setFaceStatus(
          int index, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.Builder builderForValue) {
        if (faceStatusBuilder_ == null) {
          ensureFaceStatusIsMutable();
          faceStatus_.set(index, builderForValue.build());
          onChanged();
        } else {
          faceStatusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public Builder addFaceStatus(net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus value) {
        if (faceStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFaceStatusIsMutable();
          faceStatus_.add(value);
          onChanged();
        } else {
          faceStatusBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public Builder addFaceStatus(
          int index, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus value) {
        if (faceStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFaceStatusIsMutable();
          faceStatus_.add(index, value);
          onChanged();
        } else {
          faceStatusBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public Builder addFaceStatus(
          net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.Builder builderForValue) {
        if (faceStatusBuilder_ == null) {
          ensureFaceStatusIsMutable();
          faceStatus_.add(builderForValue.build());
          onChanged();
        } else {
          faceStatusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public Builder addFaceStatus(
          int index, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.Builder builderForValue) {
        if (faceStatusBuilder_ == null) {
          ensureFaceStatusIsMutable();
          faceStatus_.add(index, builderForValue.build());
          onChanged();
        } else {
          faceStatusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public Builder addAllFaceStatus(
          java.lang.Iterable<? extends net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus> values) {
        if (faceStatusBuilder_ == null) {
          ensureFaceStatusIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, faceStatus_);
          onChanged();
        } else {
          faceStatusBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public Builder clearFaceStatus() {
        if (faceStatusBuilder_ == null) {
          faceStatus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          faceStatusBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public Builder removeFaceStatus(int index) {
        if (faceStatusBuilder_ == null) {
          ensureFaceStatusIsMutable();
          faceStatus_.remove(index);
          onChanged();
        } else {
          faceStatusBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.Builder getFaceStatusBuilder(
          int index) {
        return getFaceStatusFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatusOrBuilder getFaceStatusOrBuilder(
          int index) {
        if (faceStatusBuilder_ == null) {
          return faceStatus_.get(index);  } else {
          return faceStatusBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public java.util.List<? extends net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatusOrBuilder> 
           getFaceStatusOrBuilderList() {
        if (faceStatusBuilder_ != null) {
          return faceStatusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(faceStatus_);
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.Builder addFaceStatusBuilder() {
        return getFaceStatusFieldBuilder().addBuilder(
            net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.Builder addFaceStatusBuilder(
          int index) {
        return getFaceStatusFieldBuilder().addBuilder(
            index, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.getDefaultInstance());
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceStatusMessage.FaceStatus face_status = 128;</code>
       *
       * <pre>
       * A FaceStatusMessage has repeated FaceStatus.
       * </pre>
       */
      public java.util.List<net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.Builder> 
           getFaceStatusBuilderList() {
        return getFaceStatusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.Builder, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatusOrBuilder> 
          getFaceStatusFieldBuilder() {
        if (faceStatusBuilder_ == null) {
          faceStatusBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatus.Builder, net.named_data.jndn.tests.FaceStatusProto.FaceStatusMessage.FaceStatusOrBuilder>(
                  faceStatus_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          faceStatus_ = null;
        }
        return faceStatusBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:net.named_data.jndn.tests.FaceStatusMessage)
    }

    static {
      defaultInstance = new FaceStatusMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.named_data.jndn.tests.FaceStatusMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_named_data_jndn_tests_FaceStatusMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_named_data_jndn_tests_FaceStatusMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_named_data_jndn_tests_FaceStatusMessage_FaceStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_named_data_jndn_tests_FaceStatusMessage_FaceStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027face-status-proto.proto\022\031net.named_dat" +
      "a.jndn.tests\"\266\003\n\021FaceStatusMessage\022M\n\013fa" +
      "ce_status\030\200\001 \003(\01327.net.named_data.jndn.t" +
      "ests.FaceStatusMessage.FaceStatus\032\321\002\n\nFa" +
      "ceStatus\022\017\n\007face_id\030i \002(\004\022\013\n\003uri\030r \002(\t\022\022" +
      "\n\tlocal_uri\030\201\001 \002(\t\022\031\n\021expiration_period\030" +
      "m \001(\004\022\023\n\nface_scope\030\204\001 \002(\004\022\031\n\020face_persi" +
      "stency\030\205\001 \002(\004\022\022\n\tlink_type\030\206\001 \002(\004\022\027\n\016n_i" +
      "n_interests\030\220\001 \002(\004\022\023\n\nn_in_datas\030\221\001 \002(\004\022" +
      "\023\n\nn_in_nacks\030\227\001 \002(\004\022\030\n\017n_out_interests\030",
      "\222\001 \002(\004\022\024\n\013n_out_datas\030\223\001 \002(\004\022\024\n\013n_out_na" +
      "cks\030\230\001 \002(\004\022\023\n\nn_in_bytes\030\224\001 \002(\004\022\024\n\013n_out" +
      "_bytes\030\225\001 \002(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_net_named_data_jndn_tests_FaceStatusMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_named_data_jndn_tests_FaceStatusMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_net_named_data_jndn_tests_FaceStatusMessage_descriptor,
        new java.lang.String[] { "FaceStatus", });
    internal_static_net_named_data_jndn_tests_FaceStatusMessage_FaceStatus_descriptor =
      internal_static_net_named_data_jndn_tests_FaceStatusMessage_descriptor.getNestedTypes().get(0);
    internal_static_net_named_data_jndn_tests_FaceStatusMessage_FaceStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_net_named_data_jndn_tests_FaceStatusMessage_FaceStatus_descriptor,
        new java.lang.String[] { "FaceId", "Uri", "LocalUri", "ExpirationPeriod", "FaceScope", "FacePersistency", "LinkType", "NInInterests", "NInDatas", "NInNacks", "NOutInterests", "NOutDatas", "NOutNacks", "NInBytes", "NOutBytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
