// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: face-query-filter-proto.proto

package net.named_data.jndn.tests;

public final class FaceQueryFilterProto {
  private FaceQueryFilterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FaceQueryFilterMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
     *
     * <pre>
     * A FaceQueryFilterMessage has repeated FaceQueryFilter.
     * </pre>
     */
    java.util.List<net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter> 
        getFaceQueryFilterList();
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
     *
     * <pre>
     * A FaceQueryFilterMessage has repeated FaceQueryFilter.
     * </pre>
     */
    net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter getFaceQueryFilter(int index);
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
     *
     * <pre>
     * A FaceQueryFilterMessage has repeated FaceQueryFilter.
     * </pre>
     */
    int getFaceQueryFilterCount();
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
     *
     * <pre>
     * A FaceQueryFilterMessage has repeated FaceQueryFilter.
     * </pre>
     */
    java.util.List<? extends net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilterOrBuilder> 
        getFaceQueryFilterOrBuilderList();
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
     *
     * <pre>
     * A FaceQueryFilterMessage has repeated FaceQueryFilter.
     * </pre>
     */
    net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilterOrBuilder getFaceQueryFilterOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code net.named_data.jndn.tests.FaceQueryFilterMessage}
   *
   * <pre>
   * Protobuf has no "outer" message type, so we need to put the TLV FaceQueryFilter
   * message inside an outer "typeless" FaceQueryFilterMessage.
   * </pre>
   */
  public static final class FaceQueryFilterMessage extends
      com.google.protobuf.GeneratedMessage
      implements FaceQueryFilterMessageOrBuilder {
    // Use FaceQueryFilterMessage.newBuilder() to construct.
    private FaceQueryFilterMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FaceQueryFilterMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FaceQueryFilterMessage defaultInstance;
    public static FaceQueryFilterMessage getDefaultInstance() {
      return defaultInstance;
    }

    public FaceQueryFilterMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FaceQueryFilterMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 1202: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                faceQueryFilter_ = new java.util.ArrayList<net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter>();
                mutable_bitField0_ |= 0x00000001;
              }
              faceQueryFilter_.add(input.readMessage(net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          faceQueryFilter_ = java.util.Collections.unmodifiableList(faceQueryFilter_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.named_data.jndn.tests.FaceQueryFilterProto.internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.named_data.jndn.tests.FaceQueryFilterProto.internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.class, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<FaceQueryFilterMessage> PARSER =
        new com.google.protobuf.AbstractParser<FaceQueryFilterMessage>() {
      public FaceQueryFilterMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FaceQueryFilterMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FaceQueryFilterMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code net.named_data.jndn.tests.FaceQueryFilterMessage.FaceScope}
     */
    public enum FaceScope
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NON_LOCAL = 0;</code>
       */
      NON_LOCAL(0, 0),
      /**
       * <code>LOCAL = 1;</code>
       */
      LOCAL(1, 1),
      ;

      /**
       * <code>NON_LOCAL = 0;</code>
       */
      public static final int NON_LOCAL_VALUE = 0;
      /**
       * <code>LOCAL = 1;</code>
       */
      public static final int LOCAL_VALUE = 1;


      public final int getNumber() { return value; }

      public static FaceScope valueOf(int value) {
        switch (value) {
          case 0: return NON_LOCAL;
          case 1: return LOCAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FaceScope>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<FaceScope>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FaceScope>() {
              public FaceScope findValueByNumber(int number) {
                return FaceScope.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final FaceScope[] VALUES = values();

      public static FaceScope valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private FaceScope(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:net.named_data.jndn.tests.FaceQueryFilterMessage.FaceScope)
    }

    /**
     * Protobuf enum {@code net.named_data.jndn.tests.FaceQueryFilterMessage.FacePersistency}
     */
    public enum FacePersistency
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PERSISTENT = 0;</code>
       */
      PERSISTENT(0, 0),
      /**
       * <code>ON_DEMAND = 1;</code>
       */
      ON_DEMAND(1, 1),
      /**
       * <code>PERMANENT = 2;</code>
       */
      PERMANENT(2, 2),
      ;

      /**
       * <code>PERSISTENT = 0;</code>
       */
      public static final int PERSISTENT_VALUE = 0;
      /**
       * <code>ON_DEMAND = 1;</code>
       */
      public static final int ON_DEMAND_VALUE = 1;
      /**
       * <code>PERMANENT = 2;</code>
       */
      public static final int PERMANENT_VALUE = 2;


      public final int getNumber() { return value; }

      public static FacePersistency valueOf(int value) {
        switch (value) {
          case 0: return PERSISTENT;
          case 1: return ON_DEMAND;
          case 2: return PERMANENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FacePersistency>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<FacePersistency>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FacePersistency>() {
              public FacePersistency findValueByNumber(int number) {
                return FacePersistency.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final FacePersistency[] VALUES = values();

      public static FacePersistency valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private FacePersistency(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:net.named_data.jndn.tests.FaceQueryFilterMessage.FacePersistency)
    }

    /**
     * Protobuf enum {@code net.named_data.jndn.tests.FaceQueryFilterMessage.LinkType}
     */
    public enum LinkType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>POINT_TO_POINT = 0;</code>
       */
      POINT_TO_POINT(0, 0),
      /**
       * <code>MULTI_ACCESS = 1;</code>
       */
      MULTI_ACCESS(1, 1),
      ;

      /**
       * <code>POINT_TO_POINT = 0;</code>
       */
      public static final int POINT_TO_POINT_VALUE = 0;
      /**
       * <code>MULTI_ACCESS = 1;</code>
       */
      public static final int MULTI_ACCESS_VALUE = 1;


      public final int getNumber() { return value; }

      public static LinkType valueOf(int value) {
        switch (value) {
          case 0: return POINT_TO_POINT;
          case 1: return MULTI_ACCESS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<LinkType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<LinkType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LinkType>() {
              public LinkType findValueByNumber(int number) {
                return LinkType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.getDescriptor().getEnumTypes().get(2);
      }

      private static final LinkType[] VALUES = values();

      public static LinkType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private LinkType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:net.named_data.jndn.tests.FaceQueryFilterMessage.LinkType)
    }

    public interface FaceQueryFilterOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional uint64 face_id = 105;
      /**
       * <code>optional uint64 face_id = 105;</code>
       */
      boolean hasFaceId();
      /**
       * <code>optional uint64 face_id = 105;</code>
       */
      long getFaceId();

      // optional string uri_scheme = 131;
      /**
       * <code>optional string uri_scheme = 131;</code>
       */
      boolean hasUriScheme();
      /**
       * <code>optional string uri_scheme = 131;</code>
       */
      java.lang.String getUriScheme();
      /**
       * <code>optional string uri_scheme = 131;</code>
       */
      com.google.protobuf.ByteString
          getUriSchemeBytes();

      // optional string uri = 114;
      /**
       * <code>optional string uri = 114;</code>
       */
      boolean hasUri();
      /**
       * <code>optional string uri = 114;</code>
       */
      java.lang.String getUri();
      /**
       * <code>optional string uri = 114;</code>
       */
      com.google.protobuf.ByteString
          getUriBytes();

      // optional string local_uri = 129;
      /**
       * <code>optional string local_uri = 129;</code>
       */
      boolean hasLocalUri();
      /**
       * <code>optional string local_uri = 129;</code>
       */
      java.lang.String getLocalUri();
      /**
       * <code>optional string local_uri = 129;</code>
       */
      com.google.protobuf.ByteString
          getLocalUriBytes();

      // optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceScope face_scope = 132;
      /**
       * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceScope face_scope = 132;</code>
       */
      boolean hasFaceScope();
      /**
       * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceScope face_scope = 132;</code>
       */
      net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceScope getFaceScope();

      // optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FacePersistency face_persistency = 133;
      /**
       * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FacePersistency face_persistency = 133;</code>
       */
      boolean hasFacePersistency();
      /**
       * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FacePersistency face_persistency = 133;</code>
       */
      net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FacePersistency getFacePersistency();

      // optional .net.named_data.jndn.tests.FaceQueryFilterMessage.LinkType link_type = 134;
      /**
       * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.LinkType link_type = 134;</code>
       */
      boolean hasLinkType();
      /**
       * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.LinkType link_type = 134;</code>
       */
      net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.LinkType getLinkType();
    }
    /**
     * Protobuf type {@code net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter}
     */
    public static final class FaceQueryFilter extends
        com.google.protobuf.GeneratedMessage
        implements FaceQueryFilterOrBuilder {
      // Use FaceQueryFilter.newBuilder() to construct.
      private FaceQueryFilter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private FaceQueryFilter(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final FaceQueryFilter defaultInstance;
      public static FaceQueryFilter getDefaultInstance() {
        return defaultInstance;
      }

      public FaceQueryFilter getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private FaceQueryFilter(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 840: {
                bitField0_ |= 0x00000001;
                faceId_ = input.readUInt64();
                break;
              }
              case 914: {
                bitField0_ |= 0x00000004;
                uri_ = input.readBytes();
                break;
              }
              case 1034: {
                bitField0_ |= 0x00000008;
                localUri_ = input.readBytes();
                break;
              }
              case 1050: {
                bitField0_ |= 0x00000002;
                uriScheme_ = input.readBytes();
                break;
              }
              case 1056: {
                int rawValue = input.readEnum();
                net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceScope value = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceScope.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(132, rawValue);
                } else {
                  bitField0_ |= 0x00000010;
                  faceScope_ = value;
                }
                break;
              }
              case 1064: {
                int rawValue = input.readEnum();
                net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FacePersistency value = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FacePersistency.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(133, rawValue);
                } else {
                  bitField0_ |= 0x00000020;
                  facePersistency_ = value;
                }
                break;
              }
              case 1072: {
                int rawValue = input.readEnum();
                net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.LinkType value = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.LinkType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(134, rawValue);
                } else {
                  bitField0_ |= 0x00000040;
                  linkType_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.named_data.jndn.tests.FaceQueryFilterProto.internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_FaceQueryFilter_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.named_data.jndn.tests.FaceQueryFilterProto.internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_FaceQueryFilter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.class, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.Builder.class);
      }

      public static com.google.protobuf.Parser<FaceQueryFilter> PARSER =
          new com.google.protobuf.AbstractParser<FaceQueryFilter>() {
        public FaceQueryFilter parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new FaceQueryFilter(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<FaceQueryFilter> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional uint64 face_id = 105;
      public static final int FACE_ID_FIELD_NUMBER = 105;
      private long faceId_;
      /**
       * <code>optional uint64 face_id = 105;</code>
       */
      public boolean hasFaceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 face_id = 105;</code>
       */
      public long getFaceId() {
        return faceId_;
      }

      // optional string uri_scheme = 131;
      public static final int URI_SCHEME_FIELD_NUMBER = 131;
      private java.lang.Object uriScheme_;
      /**
       * <code>optional string uri_scheme = 131;</code>
       */
      public boolean hasUriScheme() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string uri_scheme = 131;</code>
       */
      public java.lang.String getUriScheme() {
        java.lang.Object ref = uriScheme_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uriScheme_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string uri_scheme = 131;</code>
       */
      public com.google.protobuf.ByteString
          getUriSchemeBytes() {
        java.lang.Object ref = uriScheme_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uriScheme_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string uri = 114;
      public static final int URI_FIELD_NUMBER = 114;
      private java.lang.Object uri_;
      /**
       * <code>optional string uri = 114;</code>
       */
      public boolean hasUri() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string uri = 114;</code>
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uri_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string uri = 114;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string local_uri = 129;
      public static final int LOCAL_URI_FIELD_NUMBER = 129;
      private java.lang.Object localUri_;
      /**
       * <code>optional string local_uri = 129;</code>
       */
      public boolean hasLocalUri() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string local_uri = 129;</code>
       */
      public java.lang.String getLocalUri() {
        java.lang.Object ref = localUri_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            localUri_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string local_uri = 129;</code>
       */
      public com.google.protobuf.ByteString
          getLocalUriBytes() {
        java.lang.Object ref = localUri_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceScope face_scope = 132;
      public static final int FACE_SCOPE_FIELD_NUMBER = 132;
      private net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceScope faceScope_;
      /**
       * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceScope face_scope = 132;</code>
       */
      public boolean hasFaceScope() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceScope face_scope = 132;</code>
       */
      public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceScope getFaceScope() {
        return faceScope_;
      }

      // optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FacePersistency face_persistency = 133;
      public static final int FACE_PERSISTENCY_FIELD_NUMBER = 133;
      private net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FacePersistency facePersistency_;
      /**
       * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FacePersistency face_persistency = 133;</code>
       */
      public boolean hasFacePersistency() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FacePersistency face_persistency = 133;</code>
       */
      public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FacePersistency getFacePersistency() {
        return facePersistency_;
      }

      // optional .net.named_data.jndn.tests.FaceQueryFilterMessage.LinkType link_type = 134;
      public static final int LINK_TYPE_FIELD_NUMBER = 134;
      private net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.LinkType linkType_;
      /**
       * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.LinkType link_type = 134;</code>
       */
      public boolean hasLinkType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.LinkType link_type = 134;</code>
       */
      public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.LinkType getLinkType() {
        return linkType_;
      }

      private void initFields() {
        faceId_ = 0L;
        uriScheme_ = "";
        uri_ = "";
        localUri_ = "";
        faceScope_ = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceScope.NON_LOCAL;
        facePersistency_ = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FacePersistency.PERSISTENT;
        linkType_ = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.LinkType.POINT_TO_POINT;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt64(105, faceId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(114, getUriBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(129, getLocalUriBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(131, getUriSchemeBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeEnum(132, faceScope_.getNumber());
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeEnum(133, facePersistency_.getNumber());
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeEnum(134, linkType_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(105, faceId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(114, getUriBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(129, getLocalUriBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(131, getUriSchemeBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(132, faceScope_.getNumber());
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(133, facePersistency_.getNumber());
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(134, linkType_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilterOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.named_data.jndn.tests.FaceQueryFilterProto.internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_FaceQueryFilter_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.named_data.jndn.tests.FaceQueryFilterProto.internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_FaceQueryFilter_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.class, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.Builder.class);
        }

        // Construct using net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          faceId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          uriScheme_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          uri_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          localUri_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          faceScope_ = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceScope.NON_LOCAL;
          bitField0_ = (bitField0_ & ~0x00000010);
          facePersistency_ = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FacePersistency.PERSISTENT;
          bitField0_ = (bitField0_ & ~0x00000020);
          linkType_ = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.LinkType.POINT_TO_POINT;
          bitField0_ = (bitField0_ & ~0x00000040);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.named_data.jndn.tests.FaceQueryFilterProto.internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_FaceQueryFilter_descriptor;
        }

        public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter getDefaultInstanceForType() {
          return net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.getDefaultInstance();
        }

        public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter build() {
          net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter buildPartial() {
          net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter result = new net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.faceId_ = faceId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.uriScheme_ = uriScheme_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.uri_ = uri_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.localUri_ = localUri_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.faceScope_ = faceScope_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.facePersistency_ = facePersistency_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.linkType_ = linkType_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter) {
            return mergeFrom((net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter other) {
          if (other == net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.getDefaultInstance()) return this;
          if (other.hasFaceId()) {
            setFaceId(other.getFaceId());
          }
          if (other.hasUriScheme()) {
            bitField0_ |= 0x00000002;
            uriScheme_ = other.uriScheme_;
            onChanged();
          }
          if (other.hasUri()) {
            bitField0_ |= 0x00000004;
            uri_ = other.uri_;
            onChanged();
          }
          if (other.hasLocalUri()) {
            bitField0_ |= 0x00000008;
            localUri_ = other.localUri_;
            onChanged();
          }
          if (other.hasFaceScope()) {
            setFaceScope(other.getFaceScope());
          }
          if (other.hasFacePersistency()) {
            setFacePersistency(other.getFacePersistency());
          }
          if (other.hasLinkType()) {
            setLinkType(other.getLinkType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional uint64 face_id = 105;
        private long faceId_ ;
        /**
         * <code>optional uint64 face_id = 105;</code>
         */
        public boolean hasFaceId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional uint64 face_id = 105;</code>
         */
        public long getFaceId() {
          return faceId_;
        }
        /**
         * <code>optional uint64 face_id = 105;</code>
         */
        public Builder setFaceId(long value) {
          bitField0_ |= 0x00000001;
          faceId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint64 face_id = 105;</code>
         */
        public Builder clearFaceId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          faceId_ = 0L;
          onChanged();
          return this;
        }

        // optional string uri_scheme = 131;
        private java.lang.Object uriScheme_ = "";
        /**
         * <code>optional string uri_scheme = 131;</code>
         */
        public boolean hasUriScheme() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string uri_scheme = 131;</code>
         */
        public java.lang.String getUriScheme() {
          java.lang.Object ref = uriScheme_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            uriScheme_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string uri_scheme = 131;</code>
         */
        public com.google.protobuf.ByteString
            getUriSchemeBytes() {
          java.lang.Object ref = uriScheme_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            uriScheme_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string uri_scheme = 131;</code>
         */
        public Builder setUriScheme(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          uriScheme_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string uri_scheme = 131;</code>
         */
        public Builder clearUriScheme() {
          bitField0_ = (bitField0_ & ~0x00000002);
          uriScheme_ = getDefaultInstance().getUriScheme();
          onChanged();
          return this;
        }
        /**
         * <code>optional string uri_scheme = 131;</code>
         */
        public Builder setUriSchemeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          uriScheme_ = value;
          onChanged();
          return this;
        }

        // optional string uri = 114;
        private java.lang.Object uri_ = "";
        /**
         * <code>optional string uri = 114;</code>
         */
        public boolean hasUri() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string uri = 114;</code>
         */
        public java.lang.String getUri() {
          java.lang.Object ref = uri_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            uri_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string uri = 114;</code>
         */
        public com.google.protobuf.ByteString
            getUriBytes() {
          java.lang.Object ref = uri_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            uri_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string uri = 114;</code>
         */
        public Builder setUri(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          uri_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string uri = 114;</code>
         */
        public Builder clearUri() {
          bitField0_ = (bitField0_ & ~0x00000004);
          uri_ = getDefaultInstance().getUri();
          onChanged();
          return this;
        }
        /**
         * <code>optional string uri = 114;</code>
         */
        public Builder setUriBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          uri_ = value;
          onChanged();
          return this;
        }

        // optional string local_uri = 129;
        private java.lang.Object localUri_ = "";
        /**
         * <code>optional string local_uri = 129;</code>
         */
        public boolean hasLocalUri() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional string local_uri = 129;</code>
         */
        public java.lang.String getLocalUri() {
          java.lang.Object ref = localUri_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            localUri_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string local_uri = 129;</code>
         */
        public com.google.protobuf.ByteString
            getLocalUriBytes() {
          java.lang.Object ref = localUri_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            localUri_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string local_uri = 129;</code>
         */
        public Builder setLocalUri(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          localUri_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string local_uri = 129;</code>
         */
        public Builder clearLocalUri() {
          bitField0_ = (bitField0_ & ~0x00000008);
          localUri_ = getDefaultInstance().getLocalUri();
          onChanged();
          return this;
        }
        /**
         * <code>optional string local_uri = 129;</code>
         */
        public Builder setLocalUriBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          localUri_ = value;
          onChanged();
          return this;
        }

        // optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceScope face_scope = 132;
        private net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceScope faceScope_ = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceScope.NON_LOCAL;
        /**
         * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceScope face_scope = 132;</code>
         */
        public boolean hasFaceScope() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceScope face_scope = 132;</code>
         */
        public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceScope getFaceScope() {
          return faceScope_;
        }
        /**
         * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceScope face_scope = 132;</code>
         */
        public Builder setFaceScope(net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceScope value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000010;
          faceScope_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceScope face_scope = 132;</code>
         */
        public Builder clearFaceScope() {
          bitField0_ = (bitField0_ & ~0x00000010);
          faceScope_ = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceScope.NON_LOCAL;
          onChanged();
          return this;
        }

        // optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FacePersistency face_persistency = 133;
        private net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FacePersistency facePersistency_ = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FacePersistency.PERSISTENT;
        /**
         * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FacePersistency face_persistency = 133;</code>
         */
        public boolean hasFacePersistency() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FacePersistency face_persistency = 133;</code>
         */
        public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FacePersistency getFacePersistency() {
          return facePersistency_;
        }
        /**
         * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FacePersistency face_persistency = 133;</code>
         */
        public Builder setFacePersistency(net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FacePersistency value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000020;
          facePersistency_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.FacePersistency face_persistency = 133;</code>
         */
        public Builder clearFacePersistency() {
          bitField0_ = (bitField0_ & ~0x00000020);
          facePersistency_ = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FacePersistency.PERSISTENT;
          onChanged();
          return this;
        }

        // optional .net.named_data.jndn.tests.FaceQueryFilterMessage.LinkType link_type = 134;
        private net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.LinkType linkType_ = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.LinkType.POINT_TO_POINT;
        /**
         * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.LinkType link_type = 134;</code>
         */
        public boolean hasLinkType() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.LinkType link_type = 134;</code>
         */
        public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.LinkType getLinkType() {
          return linkType_;
        }
        /**
         * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.LinkType link_type = 134;</code>
         */
        public Builder setLinkType(net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.LinkType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000040;
          linkType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .net.named_data.jndn.tests.FaceQueryFilterMessage.LinkType link_type = 134;</code>
         */
        public Builder clearLinkType() {
          bitField0_ = (bitField0_ & ~0x00000040);
          linkType_ = net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.LinkType.POINT_TO_POINT;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter)
      }

      static {
        defaultInstance = new FaceQueryFilter(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter)
    }

    // repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;
    public static final int FACE_QUERY_FILTER_FIELD_NUMBER = 150;
    private java.util.List<net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter> faceQueryFilter_;
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
     *
     * <pre>
     * A FaceQueryFilterMessage has repeated FaceQueryFilter.
     * </pre>
     */
    public java.util.List<net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter> getFaceQueryFilterList() {
      return faceQueryFilter_;
    }
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
     *
     * <pre>
     * A FaceQueryFilterMessage has repeated FaceQueryFilter.
     * </pre>
     */
    public java.util.List<? extends net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilterOrBuilder> 
        getFaceQueryFilterOrBuilderList() {
      return faceQueryFilter_;
    }
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
     *
     * <pre>
     * A FaceQueryFilterMessage has repeated FaceQueryFilter.
     * </pre>
     */
    public int getFaceQueryFilterCount() {
      return faceQueryFilter_.size();
    }
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
     *
     * <pre>
     * A FaceQueryFilterMessage has repeated FaceQueryFilter.
     * </pre>
     */
    public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter getFaceQueryFilter(int index) {
      return faceQueryFilter_.get(index);
    }
    /**
     * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
     *
     * <pre>
     * A FaceQueryFilterMessage has repeated FaceQueryFilter.
     * </pre>
     */
    public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilterOrBuilder getFaceQueryFilterOrBuilder(
        int index) {
      return faceQueryFilter_.get(index);
    }

    private void initFields() {
      faceQueryFilter_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < faceQueryFilter_.size(); i++) {
        output.writeMessage(150, faceQueryFilter_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < faceQueryFilter_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(150, faceQueryFilter_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code net.named_data.jndn.tests.FaceQueryFilterMessage}
     *
     * <pre>
     * Protobuf has no "outer" message type, so we need to put the TLV FaceQueryFilter
     * message inside an outer "typeless" FaceQueryFilterMessage.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.named_data.jndn.tests.FaceQueryFilterProto.internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.named_data.jndn.tests.FaceQueryFilterProto.internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.class, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.Builder.class);
      }

      // Construct using net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFaceQueryFilterFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (faceQueryFilterBuilder_ == null) {
          faceQueryFilter_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          faceQueryFilterBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.named_data.jndn.tests.FaceQueryFilterProto.internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_descriptor;
      }

      public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage getDefaultInstanceForType() {
        return net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.getDefaultInstance();
      }

      public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage build() {
        net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage buildPartial() {
        net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage result = new net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage(this);
        int from_bitField0_ = bitField0_;
        if (faceQueryFilterBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            faceQueryFilter_ = java.util.Collections.unmodifiableList(faceQueryFilter_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.faceQueryFilter_ = faceQueryFilter_;
        } else {
          result.faceQueryFilter_ = faceQueryFilterBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage) {
          return mergeFrom((net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage other) {
        if (other == net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.getDefaultInstance()) return this;
        if (faceQueryFilterBuilder_ == null) {
          if (!other.faceQueryFilter_.isEmpty()) {
            if (faceQueryFilter_.isEmpty()) {
              faceQueryFilter_ = other.faceQueryFilter_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFaceQueryFilterIsMutable();
              faceQueryFilter_.addAll(other.faceQueryFilter_);
            }
            onChanged();
          }
        } else {
          if (!other.faceQueryFilter_.isEmpty()) {
            if (faceQueryFilterBuilder_.isEmpty()) {
              faceQueryFilterBuilder_.dispose();
              faceQueryFilterBuilder_ = null;
              faceQueryFilter_ = other.faceQueryFilter_;
              bitField0_ = (bitField0_ & ~0x00000001);
              faceQueryFilterBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFaceQueryFilterFieldBuilder() : null;
            } else {
              faceQueryFilterBuilder_.addAllMessages(other.faceQueryFilter_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;
      private java.util.List<net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter> faceQueryFilter_ =
        java.util.Collections.emptyList();
      private void ensureFaceQueryFilterIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          faceQueryFilter_ = new java.util.ArrayList<net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter>(faceQueryFilter_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.Builder, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilterOrBuilder> faceQueryFilterBuilder_;

      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public java.util.List<net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter> getFaceQueryFilterList() {
        if (faceQueryFilterBuilder_ == null) {
          return java.util.Collections.unmodifiableList(faceQueryFilter_);
        } else {
          return faceQueryFilterBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public int getFaceQueryFilterCount() {
        if (faceQueryFilterBuilder_ == null) {
          return faceQueryFilter_.size();
        } else {
          return faceQueryFilterBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter getFaceQueryFilter(int index) {
        if (faceQueryFilterBuilder_ == null) {
          return faceQueryFilter_.get(index);
        } else {
          return faceQueryFilterBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public Builder setFaceQueryFilter(
          int index, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter value) {
        if (faceQueryFilterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFaceQueryFilterIsMutable();
          faceQueryFilter_.set(index, value);
          onChanged();
        } else {
          faceQueryFilterBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public Builder setFaceQueryFilter(
          int index, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.Builder builderForValue) {
        if (faceQueryFilterBuilder_ == null) {
          ensureFaceQueryFilterIsMutable();
          faceQueryFilter_.set(index, builderForValue.build());
          onChanged();
        } else {
          faceQueryFilterBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public Builder addFaceQueryFilter(net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter value) {
        if (faceQueryFilterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFaceQueryFilterIsMutable();
          faceQueryFilter_.add(value);
          onChanged();
        } else {
          faceQueryFilterBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public Builder addFaceQueryFilter(
          int index, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter value) {
        if (faceQueryFilterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFaceQueryFilterIsMutable();
          faceQueryFilter_.add(index, value);
          onChanged();
        } else {
          faceQueryFilterBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public Builder addFaceQueryFilter(
          net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.Builder builderForValue) {
        if (faceQueryFilterBuilder_ == null) {
          ensureFaceQueryFilterIsMutable();
          faceQueryFilter_.add(builderForValue.build());
          onChanged();
        } else {
          faceQueryFilterBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public Builder addFaceQueryFilter(
          int index, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.Builder builderForValue) {
        if (faceQueryFilterBuilder_ == null) {
          ensureFaceQueryFilterIsMutable();
          faceQueryFilter_.add(index, builderForValue.build());
          onChanged();
        } else {
          faceQueryFilterBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public Builder addAllFaceQueryFilter(
          java.lang.Iterable<? extends net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter> values) {
        if (faceQueryFilterBuilder_ == null) {
          ensureFaceQueryFilterIsMutable();
          super.addAll(values, faceQueryFilter_);
          onChanged();
        } else {
          faceQueryFilterBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public Builder clearFaceQueryFilter() {
        if (faceQueryFilterBuilder_ == null) {
          faceQueryFilter_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          faceQueryFilterBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public Builder removeFaceQueryFilter(int index) {
        if (faceQueryFilterBuilder_ == null) {
          ensureFaceQueryFilterIsMutable();
          faceQueryFilter_.remove(index);
          onChanged();
        } else {
          faceQueryFilterBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.Builder getFaceQueryFilterBuilder(
          int index) {
        return getFaceQueryFilterFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilterOrBuilder getFaceQueryFilterOrBuilder(
          int index) {
        if (faceQueryFilterBuilder_ == null) {
          return faceQueryFilter_.get(index);  } else {
          return faceQueryFilterBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public java.util.List<? extends net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilterOrBuilder> 
           getFaceQueryFilterOrBuilderList() {
        if (faceQueryFilterBuilder_ != null) {
          return faceQueryFilterBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(faceQueryFilter_);
        }
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.Builder addFaceQueryFilterBuilder() {
        return getFaceQueryFilterFieldBuilder().addBuilder(
            net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.getDefaultInstance());
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.Builder addFaceQueryFilterBuilder(
          int index) {
        return getFaceQueryFilterFieldBuilder().addBuilder(
            index, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.getDefaultInstance());
      }
      /**
       * <code>repeated .net.named_data.jndn.tests.FaceQueryFilterMessage.FaceQueryFilter face_query_filter = 150;</code>
       *
       * <pre>
       * A FaceQueryFilterMessage has repeated FaceQueryFilter.
       * </pre>
       */
      public java.util.List<net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.Builder> 
           getFaceQueryFilterBuilderList() {
        return getFaceQueryFilterFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.Builder, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilterOrBuilder> 
          getFaceQueryFilterFieldBuilder() {
        if (faceQueryFilterBuilder_ == null) {
          faceQueryFilterBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilter.Builder, net.named_data.jndn.tests.FaceQueryFilterProto.FaceQueryFilterMessage.FaceQueryFilterOrBuilder>(
                  faceQueryFilter_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          faceQueryFilter_ = null;
        }
        return faceQueryFilterBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:net.named_data.jndn.tests.FaceQueryFilterMessage)
    }

    static {
      defaultInstance = new FaceQueryFilterMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:net.named_data.jndn.tests.FaceQueryFilterMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_FaceQueryFilter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_FaceQueryFilter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035face-query-filter-proto.proto\022\031net.nam" +
      "ed_data.jndn.tests\"\354\004\n\026FaceQueryFilterMe" +
      "ssage\022]\n\021face_query_filter\030\226\001 \003(\0132A.net." +
      "named_data.jndn.tests.FaceQueryFilterMes" +
      "sage.FaceQueryFilter\032\330\002\n\017FaceQueryFilter" +
      "\022\017\n\007face_id\030i \001(\004\022\023\n\nuri_scheme\030\203\001 \001(\t\022\013" +
      "\n\003uri\030r \001(\t\022\022\n\tlocal_uri\030\201\001 \001(\t\022P\n\nface_" +
      "scope\030\204\001 \001(\0162;.net.named_data.jndn.tests" +
      ".FaceQueryFilterMessage.FaceScope\022\\\n\020fac" +
      "e_persistency\030\205\001 \001(\0162A.net.named_data.jn",
      "dn.tests.FaceQueryFilterMessage.FacePers" +
      "istency\022N\n\tlink_type\030\206\001 \001(\0162:.net.named_" +
      "data.jndn.tests.FaceQueryFilterMessage.L" +
      "inkType\"%\n\tFaceScope\022\r\n\tNON_LOCAL\020\000\022\t\n\005L" +
      "OCAL\020\001\"?\n\017FacePersistency\022\016\n\nPERSISTENT\020" +
      "\000\022\r\n\tON_DEMAND\020\001\022\r\n\tPERMANENT\020\002\"0\n\010LinkT" +
      "ype\022\022\n\016POINT_TO_POINT\020\000\022\020\n\014MULTI_ACCESS\020" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_descriptor,
              new java.lang.String[] { "FaceQueryFilter", });
          internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_FaceQueryFilter_descriptor =
            internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_descriptor.getNestedTypes().get(0);
          internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_FaceQueryFilter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_named_data_jndn_tests_FaceQueryFilterMessage_FaceQueryFilter_descriptor,
              new java.lang.String[] { "FaceId", "UriScheme", "Uri", "LocalUri", "FaceScope", "FacePersistency", "LinkType", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
